// Code generated by protoc-gen-go. DO NOT EDIT.
// This is a hand-written stub matching the proto definition.
// In production, run: protoc --go_out=. --go-grpc_out=. proto/mta.proto

package proto

// SendRequest represents a single email send request.
type SendRequest struct {
	MessageId     string            `json:"message_id"`
	FromEmail     string            `json:"from_email"`
	FromName      string            `json:"from_name"`
	ToEmail       string            `json:"to_email"`
	ToName        string            `json:"to_name"`
	Subject       string            `json:"subject"`
	HtmlBody      string            `json:"html_body"`
	TextBody      string            `json:"text_body"`
	ReplyTo       string            `json:"reply_to"`
	Dkim          *DkimConfig       `json:"dkim"`
	CustomHeaders map[string]string `json:"custom_headers"`
	OrgId         string            `json:"org_id"`
	CampaignId    string            `json:"campaign_id"`
	ContactId     string            `json:"contact_id"`
	SendingIp     string            `json:"sending_ip"`
}

// DkimConfig holds DKIM signing configuration.
type DkimConfig struct {
	Domain        string `json:"domain"`
	Selector      string `json:"selector"`
	PrivateKeyPem string `json:"private_key_pem"`
}

// SendResponse is the result of a single send attempt.
type SendResponse struct {
	Success     bool   `json:"success"`
	MessageId   string `json:"message_id"`
	SmtpCode    int32  `json:"smtp_code"`
	SmtpMessage string `json:"smtp_message"`
	Error       string `json:"error"`
	DurationMs  int64  `json:"duration_ms"`
}

// SendBatchRequest wraps multiple send requests.
type SendBatchRequest struct {
	Messages []*SendRequest `json:"messages"`
}

// SendBatchResponse wraps multiple send responses.
type SendBatchResponse struct {
	Results     []*SendResponse `json:"results"`
	TotalSent   int32           `json:"total_sent"`
	TotalFailed int32           `json:"total_failed"`
}

// HealthCheckRequest is empty.
type HealthCheckRequest struct{}

// HealthCheckResponse reports MTA health.
type HealthCheckResponse struct {
	Healthy           bool   `json:"healthy"`
	ActiveConnections int32  `json:"active_connections"`
	PoolSize          int32  `json:"pool_size"`
	Version           string `json:"version"`
}
