// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/mta.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	MessageId string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	FromEmail string                 `protobuf:"bytes,2,opt,name=from_email,json=fromEmail,proto3" json:"from_email,omitempty"`
	FromName  string                 `protobuf:"bytes,3,opt,name=from_name,json=fromName,proto3" json:"from_name,omitempty"`
	ToEmail   string                 `protobuf:"bytes,4,opt,name=to_email,json=toEmail,proto3" json:"to_email,omitempty"`
	ToName    string                 `protobuf:"bytes,5,opt,name=to_name,json=toName,proto3" json:"to_name,omitempty"`
	Subject   string                 `protobuf:"bytes,6,opt,name=subject,proto3" json:"subject,omitempty"`
	HtmlBody  string                 `protobuf:"bytes,7,opt,name=html_body,json=htmlBody,proto3" json:"html_body,omitempty"`
	TextBody  string                 `protobuf:"bytes,8,opt,name=text_body,json=textBody,proto3" json:"text_body,omitempty"`
	ReplyTo   string                 `protobuf:"bytes,9,opt,name=reply_to,json=replyTo,proto3" json:"reply_to,omitempty"`
	// DKIM signing config
	Dkim *DkimConfig `protobuf:"bytes,10,opt,name=dkim,proto3" json:"dkim,omitempty"`
	// Custom headers (List-Unsubscribe, etc.)
	CustomHeaders map[string]string `protobuf:"bytes,11,rep,name=custom_headers,json=customHeaders,proto3" json:"custom_headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Metadata for tracking
	OrgId      string `protobuf:"bytes,12,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	CampaignId string `protobuf:"bytes,13,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	ContactId  string `protobuf:"bytes,14,opt,name=contact_id,json=contactId,proto3" json:"contact_id,omitempty"`
	// Sending IP override (empty = use default pool)
	SendingIp string `protobuf:"bytes,15,opt,name=sending_ip,json=sendingIp,proto3" json:"sending_ip,omitempty"`
	// File attachments (e.g. e-ticket PDFs). Empty for link-only emails.
	Attachments []*Attachment `protobuf:"bytes,16,rep,name=attachments,proto3" json:"attachments,omitempty"`
	// VERP envelope sender (Return-Path / SMTP MAIL FROM). Empty = use from_email.
	// Encodes the message so out-of-band bounces can be attributed.
	ReturnPath    string `protobuf:"bytes,17,opt,name=return_path,json=returnPath,proto3" json:"return_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendRequest) Reset() {
	*x = SendRequest{}
	mi := &file_proto_mta_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendRequest) ProtoMessage() {}

func (x *SendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mta_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendRequest.ProtoReflect.Descriptor instead.
func (*SendRequest) Descriptor() ([]byte, []int) {
	return file_proto_mta_proto_rawDescGZIP(), []int{0}
}

func (x *SendRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *SendRequest) GetFromEmail() string {
	if x != nil {
		return x.FromEmail
	}
	return ""
}

func (x *SendRequest) GetFromName() string {
	if x != nil {
		return x.FromName
	}
	return ""
}

func (x *SendRequest) GetToEmail() string {
	if x != nil {
		return x.ToEmail
	}
	return ""
}

func (x *SendRequest) GetToName() string {
	if x != nil {
		return x.ToName
	}
	return ""
}

func (x *SendRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *SendRequest) GetHtmlBody() string {
	if x != nil {
		return x.HtmlBody
	}
	return ""
}

func (x *SendRequest) GetTextBody() string {
	if x != nil {
		return x.TextBody
	}
	return ""
}

func (x *SendRequest) GetReplyTo() string {
	if x != nil {
		return x.ReplyTo
	}
	return ""
}

func (x *SendRequest) GetDkim() *DkimConfig {
	if x != nil {
		return x.Dkim
	}
	return nil
}

func (x *SendRequest) GetCustomHeaders() map[string]string {
	if x != nil {
		return x.CustomHeaders
	}
	return nil
}

func (x *SendRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *SendRequest) GetCampaignId() string {
	if x != nil {
		return x.CampaignId
	}
	return ""
}

func (x *SendRequest) GetContactId() string {
	if x != nil {
		return x.ContactId
	}
	return ""
}

func (x *SendRequest) GetSendingIp() string {
	if x != nil {
		return x.SendingIp
	}
	return ""
}

func (x *SendRequest) GetAttachments() []*Attachment {
	if x != nil {
		return x.Attachments
	}
	return nil
}

func (x *SendRequest) GetReturnPath() string {
	if x != nil {
		return x.ReturnPath
	}
	return ""
}

type Attachment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	ContentType   string                 `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"` // MIME type, e.g. "application/pdf"
	Content       []byte                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`                            // raw bytes (base64 on the wire via proto)
	ContentId     string                 `protobuf:"bytes,4,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`       // for inline images referenced as cid:<id>
	Inline        bool                   `protobuf:"varint,5,opt,name=inline,proto3" json:"inline,omitempty"`                             // true = inline (Content-Disposition: inline)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Attachment) Reset() {
	*x = Attachment{}
	mi := &file_proto_mta_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Attachment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attachment) ProtoMessage() {}

func (x *Attachment) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mta_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attachment.ProtoReflect.Descriptor instead.
func (*Attachment) Descriptor() ([]byte, []int) {
	return file_proto_mta_proto_rawDescGZIP(), []int{1}
}

func (x *Attachment) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *Attachment) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *Attachment) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *Attachment) GetContentId() string {
	if x != nil {
		return x.ContentId
	}
	return ""
}

func (x *Attachment) GetInline() bool {
	if x != nil {
		return x.Inline
	}
	return false
}

type DkimConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	Selector      string                 `protobuf:"bytes,2,opt,name=selector,proto3" json:"selector,omitempty"`
	PrivateKeyPem string                 `protobuf:"bytes,3,opt,name=private_key_pem,json=privateKeyPem,proto3" json:"private_key_pem,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DkimConfig) Reset() {
	*x = DkimConfig{}
	mi := &file_proto_mta_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DkimConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DkimConfig) ProtoMessage() {}

func (x *DkimConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mta_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DkimConfig.ProtoReflect.Descriptor instead.
func (*DkimConfig) Descriptor() ([]byte, []int) {
	return file_proto_mta_proto_rawDescGZIP(), []int{2}
}

func (x *DkimConfig) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *DkimConfig) GetSelector() string {
	if x != nil {
		return x.Selector
	}
	return ""
}

func (x *DkimConfig) GetPrivateKeyPem() string {
	if x != nil {
		return x.PrivateKeyPem
	}
	return ""
}

type SendResponse struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Success     bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	MessageId   string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	SmtpCode    int32                  `protobuf:"varint,3,opt,name=smtp_code,json=smtpCode,proto3" json:"smtp_code,omitempty"`
	SmtpMessage string                 `protobuf:"bytes,4,opt,name=smtp_message,json=smtpMessage,proto3" json:"smtp_message,omitempty"`
	Error       string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	// Duration in milliseconds
	DurationMs    int64 `protobuf:"varint,6,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendResponse) Reset() {
	*x = SendResponse{}
	mi := &file_proto_mta_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendResponse) ProtoMessage() {}

func (x *SendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mta_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendResponse.ProtoReflect.Descriptor instead.
func (*SendResponse) Descriptor() ([]byte, []int) {
	return file_proto_mta_proto_rawDescGZIP(), []int{3}
}

func (x *SendResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SendResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *SendResponse) GetSmtpCode() int32 {
	if x != nil {
		return x.SmtpCode
	}
	return 0
}

func (x *SendResponse) GetSmtpMessage() string {
	if x != nil {
		return x.SmtpMessage
	}
	return ""
}

func (x *SendResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *SendResponse) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

type SendBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*SendRequest         `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendBatchRequest) Reset() {
	*x = SendBatchRequest{}
	mi := &file_proto_mta_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendBatchRequest) ProtoMessage() {}

func (x *SendBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mta_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendBatchRequest.ProtoReflect.Descriptor instead.
func (*SendBatchRequest) Descriptor() ([]byte, []int) {
	return file_proto_mta_proto_rawDescGZIP(), []int{4}
}

func (x *SendBatchRequest) GetMessages() []*SendRequest {
	if x != nil {
		return x.Messages
	}
	return nil
}

type SendBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*SendResponse        `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	TotalSent     int32                  `protobuf:"varint,2,opt,name=total_sent,json=totalSent,proto3" json:"total_sent,omitempty"`
	TotalFailed   int32                  `protobuf:"varint,3,opt,name=total_failed,json=totalFailed,proto3" json:"total_failed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendBatchResponse) Reset() {
	*x = SendBatchResponse{}
	mi := &file_proto_mta_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendBatchResponse) ProtoMessage() {}

func (x *SendBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mta_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendBatchResponse.ProtoReflect.Descriptor instead.
func (*SendBatchResponse) Descriptor() ([]byte, []int) {
	return file_proto_mta_proto_rawDescGZIP(), []int{5}
}

func (x *SendBatchResponse) GetResults() []*SendResponse {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *SendBatchResponse) GetTotalSent() int32 {
	if x != nil {
		return x.TotalSent
	}
	return 0
}

func (x *SendBatchResponse) GetTotalFailed() int32 {
	if x != nil {
		return x.TotalFailed
	}
	return 0
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_proto_mta_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mta_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_proto_mta_proto_rawDescGZIP(), []int{6}
}

type HealthCheckResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Healthy           bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	ActiveConnections int32                  `protobuf:"varint,2,opt,name=active_connections,json=activeConnections,proto3" json:"active_connections,omitempty"`
	PoolSize          int32                  `protobuf:"varint,3,opt,name=pool_size,json=poolSize,proto3" json:"pool_size,omitempty"`
	Version           string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_proto_mta_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mta_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_proto_mta_proto_rawDescGZIP(), []int{7}
}

func (x *HealthCheckResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthCheckResponse) GetActiveConnections() int32 {
	if x != nil {
		return x.ActiveConnections
	}
	return 0
}

func (x *HealthCheckResponse) GetPoolSize() int32 {
	if x != nil {
		return x.PoolSize
	}
	return 0
}

func (x *HealthCheckResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

var File_proto_mta_proto protoreflect.FileDescriptor

const file_proto_mta_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/mta.proto\x12\x03mta\"\x88\x05\n" +
	"\vSendRequest\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x1d\n" +
	"\n" +
	"from_email\x18\x02 \x01(\tR\tfromEmail\x12\x1b\n" +
	"\tfrom_name\x18\x03 \x01(\tR\bfromName\x12\x19\n" +
	"\bto_email\x18\x04 \x01(\tR\atoEmail\x12\x17\n" +
	"\ato_name\x18\x05 \x01(\tR\x06toName\x12\x18\n" +
	"\asubject\x18\x06 \x01(\tR\asubject\x12\x1b\n" +
	"\thtml_body\x18\a \x01(\tR\bhtmlBody\x12\x1b\n" +
	"\ttext_body\x18\b \x01(\tR\btextBody\x12\x19\n" +
	"\breply_to\x18\t \x01(\tR\areplyTo\x12#\n" +
	"\x04dkim\x18\n" +
	" \x01(\v2\x0f.mta.DkimConfigR\x04dkim\x12J\n" +
	"\x0ecustom_headers\x18\v \x03(\v2#.mta.SendRequest.CustomHeadersEntryR\rcustomHeaders\x12\x15\n" +
	"\x06org_id\x18\f \x01(\tR\x05orgId\x12\x1f\n" +
	"\vcampaign_id\x18\r \x01(\tR\n" +
	"campaignId\x12\x1d\n" +
	"\n" +
	"contact_id\x18\x0e \x01(\tR\tcontactId\x12\x1d\n" +
	"\n" +
	"sending_ip\x18\x0f \x01(\tR\tsendingIp\x121\n" +
	"\vattachments\x18\x10 \x03(\v2\x0f.mta.AttachmentR\vattachments\x12\x1f\n" +
	"\vreturn_path\x18\x11 \x01(\tR\n" +
	"returnPath\x1a@\n" +
	"\x12CustomHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9c\x01\n" +
	"\n" +
	"Attachment\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\x12\x18\n" +
	"\acontent\x18\x03 \x01(\fR\acontent\x12\x1d\n" +
	"\n" +
	"content_id\x18\x04 \x01(\tR\tcontentId\x12\x16\n" +
	"\x06inline\x18\x05 \x01(\bR\x06inline\"h\n" +
	"\n" +
	"DkimConfig\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x12\x1a\n" +
	"\bselector\x18\x02 \x01(\tR\bselector\x12&\n" +
	"\x0fprivate_key_pem\x18\x03 \x01(\tR\rprivateKeyPem\"\xbe\x01\n" +
	"\fSendResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\x12\x1b\n" +
	"\tsmtp_code\x18\x03 \x01(\x05R\bsmtpCode\x12!\n" +
	"\fsmtp_message\x18\x04 \x01(\tR\vsmtpMessage\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\x12\x1f\n" +
	"\vduration_ms\x18\x06 \x01(\x03R\n" +
	"durationMs\"@\n" +
	"\x10SendBatchRequest\x12,\n" +
	"\bmessages\x18\x01 \x03(\v2\x10.mta.SendRequestR\bmessages\"\x82\x01\n" +
	"\x11SendBatchResponse\x12+\n" +
	"\aresults\x18\x01 \x03(\v2\x11.mta.SendResponseR\aresults\x12\x1d\n" +
	"\n" +
	"total_sent\x18\x02 \x01(\x05R\ttotalSent\x12!\n" +
	"\ftotal_failed\x18\x03 \x01(\x05R\vtotalFailed\"\x14\n" +
	"\x12HealthCheckRequest\"\x95\x01\n" +
	"\x13HealthCheckResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12-\n" +
	"\x12active_connections\x18\x02 \x01(\x05R\x11activeConnections\x12\x1b\n" +
	"\tpool_size\x18\x03 \x01(\x05R\bpoolSize\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion2\xb7\x01\n" +
	"\n" +
	"MTAService\x12+\n" +
	"\x04Send\x12\x10.mta.SendRequest\x1a\x11.mta.SendResponse\x12:\n" +
	"\tSendBatch\x12\x15.mta.SendBatchRequest\x1a\x16.mta.SendBatchResponse\x12@\n" +
	"\vHealthCheck\x12\x17.mta.HealthCheckRequest\x1a\x18.mta.HealthCheckResponseB\"Z github.com/forgemsg/engine/protob\x06proto3"

var (
	file_proto_mta_proto_rawDescOnce sync.Once
	file_proto_mta_proto_rawDescData []byte
)

func file_proto_mta_proto_rawDescGZIP() []byte {
	file_proto_mta_proto_rawDescOnce.Do(func() {
		file_proto_mta_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_mta_proto_rawDesc), len(file_proto_mta_proto_rawDesc)))
	})
	return file_proto_mta_proto_rawDescData
}

var file_proto_mta_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_mta_proto_goTypes = []any{
	(*SendRequest)(nil),         // 0: mta.SendRequest
	(*Attachment)(nil),          // 1: mta.Attachment
	(*DkimConfig)(nil),          // 2: mta.DkimConfig
	(*SendResponse)(nil),        // 3: mta.SendResponse
	(*SendBatchRequest)(nil),    // 4: mta.SendBatchRequest
	(*SendBatchResponse)(nil),   // 5: mta.SendBatchResponse
	(*HealthCheckRequest)(nil),  // 6: mta.HealthCheckRequest
	(*HealthCheckResponse)(nil), // 7: mta.HealthCheckResponse
	nil,                         // 8: mta.SendRequest.CustomHeadersEntry
}
var file_proto_mta_proto_depIdxs = []int32{
	2, // 0: mta.SendRequest.dkim:type_name -> mta.DkimConfig
	8, // 1: mta.SendRequest.custom_headers:type_name -> mta.SendRequest.CustomHeadersEntry
	1, // 2: mta.SendRequest.attachments:type_name -> mta.Attachment
	0, // 3: mta.SendBatchRequest.messages:type_name -> mta.SendRequest
	3, // 4: mta.SendBatchResponse.results:type_name -> mta.SendResponse
	0, // 5: mta.MTAService.Send:input_type -> mta.SendRequest
	4, // 6: mta.MTAService.SendBatch:input_type -> mta.SendBatchRequest
	6, // 7: mta.MTAService.HealthCheck:input_type -> mta.HealthCheckRequest
	3, // 8: mta.MTAService.Send:output_type -> mta.SendResponse
	5, // 9: mta.MTAService.SendBatch:output_type -> mta.SendBatchResponse
	7, // 10: mta.MTAService.HealthCheck:output_type -> mta.HealthCheckResponse
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_mta_proto_init() }
func file_proto_mta_proto_init() {
	if File_proto_mta_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_mta_proto_rawDesc), len(file_proto_mta_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_mta_proto_goTypes,
		DependencyIndexes: file_proto_mta_proto_depIdxs,
		MessageInfos:      file_proto_mta_proto_msgTypes,
	}.Build()
	File_proto_mta_proto = out.File
	file_proto_mta_proto_goTypes = nil
	file_proto_mta_proto_depIdxs = nil
}
