// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// This is a hand-written stub matching the proto definition.
// In production, run: protoc --go_out=. --go-grpc_out=. proto/mta.proto

package proto

import (
	"context"

	"google.golang.org/grpc"
)

// MTAServiceServer is the server API for MTAService.
type MTAServiceServer interface {
	Send(context.Context, *SendRequest) (*SendResponse, error)
	SendBatch(context.Context, *SendBatchRequest) (*SendBatchResponse, error)
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
}

// UnimplementedMTAServiceServer should be embedded to have forward compatible implementations.
type UnimplementedMTAServiceServer struct{}

func (UnimplementedMTAServiceServer) Send(context.Context, *SendRequest) (*SendResponse, error) {
	return nil, grpc.Errorf(12, "method Send not implemented") //nolint:staticcheck
}
func (UnimplementedMTAServiceServer) SendBatch(context.Context, *SendBatchRequest) (*SendBatchResponse, error) {
	return nil, grpc.Errorf(12, "method SendBatch not implemented") //nolint:staticcheck
}
func (UnimplementedMTAServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, grpc.Errorf(12, "method HealthCheck not implemented") //nolint:staticcheck
}

// RegisterMTAServiceServer registers the MTAServiceServer with the grpc.Server.
func RegisterMTAServiceServer(s *grpc.Server, srv MTAServiceServer) {
	s.RegisterService(&_MTAService_serviceDesc, srv)
}

var _MTAService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mta.MTAService",
	HandlerType: (*MTAServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Send",
			Handler: func(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
				in := new(SendRequest)
				if err := dec(in); err != nil {
					return nil, err
				}
				if interceptor == nil {
					return srv.(MTAServiceServer).Send(ctx, in)
				}
				info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/mta.MTAService/Send"}
				return interceptor(ctx, in, info, func(ctx context.Context, req interface{}) (interface{}, error) {
					return srv.(MTAServiceServer).Send(ctx, req.(*SendRequest))
				})
			},
		},
		{
			MethodName: "SendBatch",
			Handler: func(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
				in := new(SendBatchRequest)
				if err := dec(in); err != nil {
					return nil, err
				}
				if interceptor == nil {
					return srv.(MTAServiceServer).SendBatch(ctx, in)
				}
				info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/mta.MTAService/SendBatch"}
				return interceptor(ctx, in, info, func(ctx context.Context, req interface{}) (interface{}, error) {
					return srv.(MTAServiceServer).SendBatch(ctx, req.(*SendBatchRequest))
				})
			},
		},
		{
			MethodName: "HealthCheck",
			Handler: func(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
				in := new(HealthCheckRequest)
				if err := dec(in); err != nil {
					return nil, err
				}
				if interceptor == nil {
					return srv.(MTAServiceServer).HealthCheck(ctx, in)
				}
				info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/mta.MTAService/HealthCheck"}
				return interceptor(ctx, in, info, func(ctx context.Context, req interface{}) (interface{}, error) {
					return srv.(MTAServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
				})
			},
		},
	},
	Streams: []grpc.StreamDesc{},
}

// MTAServiceClient is the client API for MTAService.
type MTAServiceClient interface {
	Send(ctx context.Context, in *SendRequest, opts ...grpc.CallOption) (*SendResponse, error)
	SendBatch(ctx context.Context, in *SendBatchRequest, opts ...grpc.CallOption) (*SendBatchResponse, error)
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type mtaServiceClient struct {
	cc grpc.ClientConnInterface
}

// NewMTAServiceClient creates a new gRPC client for the MTA service.
func NewMTAServiceClient(cc grpc.ClientConnInterface) MTAServiceClient {
	return &mtaServiceClient{cc}
}

func (c *mtaServiceClient) Send(ctx context.Context, in *SendRequest, opts ...grpc.CallOption) (*SendResponse, error) {
	out := new(SendResponse)
	err := c.cc.Invoke(ctx, "/mta.MTAService/Send", in, out, opts...)
	return out, err
}

func (c *mtaServiceClient) SendBatch(ctx context.Context, in *SendBatchRequest, opts ...grpc.CallOption) (*SendBatchResponse, error) {
	out := new(SendBatchResponse)
	err := c.cc.Invoke(ctx, "/mta.MTAService/SendBatch", in, out, opts...)
	return out, err
}

func (c *mtaServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, "/mta.MTAService/HealthCheck", in, out, opts...)
	return out, err
}
