/**
 * AI Calendly Smart-Schedule block (#211)
 *
 * Renders a self-contained HTML scheduling widget for email:
 *   - Shows N clickable time slots (pre-generated by smart-slot.ts)
 *   - Each slot is a mailto: or booking URL button
 *   - Falls back to a generic "Book a time" CTA if no slots provided
 *
 * Designed to be embedded as a block in the email schema JSON, or used
 * standalone by the 1:1 email sender.
 *
 * The block itself is pure HTML (no JS) — links open a booking page where
 * the slot is pre-selected. This is necessary because email clients block JS.
 */

export interface SmartScheduleSlot {
  startUtc: string;
  endUtc: string;
  localDisplay: string;
  timezone: string;
}

export interface SmartScheduleBlockOptions {
  /** Sender/rep display name shown above the slots */
  senderName: string;
  /** Intro text */
  intro?: string;
  /** Booking base URL — slot startUtc is appended as `?slot=<encoded>` */
  bookingUrl: string;
  /** Pre-computed slots from smart-slot.ts */
  slots: SmartScheduleSlot[];
  /** Primary color for buttons (hex or CSS color) */
  primaryColor?: string;
  /** Fallback CTA text if slots is empty */
  fallbackCta?: string;
}

/**
 * Renders the scheduling block as HTML safe for email clients.
 * Returns a self-contained <table>-based widget.
 */
export function renderSmartScheduleBlock(opts: SmartScheduleBlockOptions): string {
  const {
    senderName,
    intro = `Pick a time that works for you:`,
    bookingUrl,
    slots,
    primaryColor = '#4F46E5',
    fallbackCta = 'Book a meeting',
  } = opts;

  const slotButtons = slots.length > 0
    ? slots.map((slot) => {
      const encoded = encodeURIComponent(slot.startUtc);
      const url = `${bookingUrl}?slot=${encoded}&tz=${encodeURIComponent(slot.timezone)}`;
      return `
        <tr>
          <td align="center" style="padding:4px 0;">
            <a href="${escapeAttr(url)}"
               style="
                 display:inline-block;
                 background-color:${escapeAttr(primaryColor)};
                 color:#ffffff;
                 font-family:Arial,Helvetica,sans-serif;
                 font-size:14px;
                 font-weight:600;
                 text-decoration:none;
                 padding:10px 24px;
                 border-radius:6px;
                 mso-padding-alt:0;
               ">
              ${escapeHtml(slot.localDisplay)}
            </a>
          </td>
        </tr>`;
    }).join('\n')
    : `
      <tr>
        <td align="center" style="padding:4px 0;">
          <a href="${escapeAttr(bookingUrl)}"
             style="
               display:inline-block;
               background-color:${escapeAttr(primaryColor)};
               color:#ffffff;
               font-family:Arial,Helvetica,sans-serif;
               font-size:14px;
               font-weight:600;
               text-decoration:none;
               padding:10px 24px;
               border-radius:6px;
             ">
            ${escapeHtml(fallbackCta)}
          </a>
        </td>
      </tr>`;

  return `
<!-- [ForgeMsg Smart Schedule Block] -->
<table width="100%" cellpadding="0" cellspacing="0" border="0"
       style="max-width:480px;margin:0 auto;background:#f9f9f9;border-radius:8px;padding:24px;font-family:Arial,Helvetica,sans-serif;">
  <tr>
    <td align="center" style="padding-bottom:12px;">
      <p style="margin:0;font-size:15px;color:#111827;font-weight:600;">${escapeHtml(senderName)} — Schedule a Call</p>
    </td>
  </tr>
  <tr>
    <td align="center" style="padding-bottom:16px;">
      <p style="margin:0;font-size:14px;color:#6b7280;">${escapeHtml(intro)}</p>
    </td>
  </tr>
  ${slotButtons}
  ${slots.length > 0 ? `
  <tr>
    <td align="center" style="padding-top:12px;">
      <a href="${escapeAttr(bookingUrl)}" style="font-size:12px;color:#6b7280;">See all available times</a>
    </td>
  </tr>` : ''}
</table>
<!-- [/ForgeMsg Smart Schedule Block] -->`.trim();
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function escapeAttr(str: string): string {
  return str.replace(/"/g, '&quot;').replace(/'/g, '&#39;');
}
