// Env validation runs first so missing JWT_SECRET / DATABASE_URL fails
// the boot with a clear message before any plugin tries to use them.
import './lib/env.js';
// Sentry next — has to wrap the runtime as early as possible to instrument
// http/console. No-op when SENTRY_DSN is unset (dev + tests).
import { initTelemetry } from './lib/telemetry.js';
initTelemetry();

import crypto from 'node:crypto';
import Fastify from 'fastify';
import errorHandler from './plugins/error-handler.js';
import helmetPlugin from './plugins/helmet.js';
import swaggerPlugin from './plugins/swagger.js';
import corsPlugin from './plugins/cors.js';
import rateLimitPlugin from './plugins/rate-limit.js';
import cookiePlugin from './plugins/cookie.js';
import authPlugin from './plugins/auth.js';
import auditPlugin from './plugins/audit.js';
import ipRestrictionsPlugin from './plugins/ip-restrictions.js';
import multipartPlugin from './plugins/multipart.js';
import healthRoutes from './routes/v1/health.js';
import superadminRoutes from './routes/v1/superadmin.js';
import contactRoutes from './routes/v1/contacts.js';
import contactImportRoutes from './routes/v1/contact-imports.js';
import authRoutes from './routes/v1/auth.js';
import segmentRoutes from './routes/v1/segments.js';
import frequencyRoutes from './routes/v1/frequency-rules.js';
import tagRoutes from './routes/v1/tags.js';
import customFieldRoutes from './routes/v1/custom-fields.js';
import suppressionRoutes from './routes/v1/suppressions.js';
import subscriptionRoutes from './routes/v1/subscriptions.js';
import listRoutes from './routes/v1/lists.js';
import organizationRoutes from './routes/v1/organizations.js';
import aiRoutes from './routes/v1/ai.js';
import editorRoutes from './routes/v1/editor.js';
import templateRoutes from './routes/v1/templates.js';
import domainRoutes from './routes/v1/domains.js';
import sendingRoutes from './routes/v1/sending.js';
import trackingRoutes from './routes/v1/tracking.js';
import preferenceCenterRoutes from './routes/v1/preference-center.js';
import consentRoutes from './routes/v1/consent.js';
import campaignRoutes from './routes/v1/campaigns.js';
import analyticsRoutes from './routes/v1/analytics.js';
import statsCategoryRoutes from './routes/v1/stats-categories.js';
import mailSettingsRoutes from './routes/v1/mail-settings.js';
import seedTestRoutes from './routes/v1/seed-tests.js';
import alertRoutes from './routes/v1/alerts.js';
import workflowRoutes from './routes/v1/workflows.js';
import eventRoutes from './routes/v1/events.js';
import leadScoringRoutes from './routes/v1/lead-scoring.js';
import webhookRoutes from './routes/v1/webhooks.js';
import signupFormRoutes from './routes/v1/signup-forms.js';
import migrationRoutes from './routes/v1/migrations.js';
import smsRoutes from './routes/v1/sms.js';
import whatsappRoutes from './routes/v1/whatsapp.js';
import pushRoutes from './routes/v1/push.js';
import inAppRoutes from './routes/v1/in-app.js';
import voiceRoutes from './routes/v1/voice.js';
import sendOptimizationRoutes from './routes/v1/send-optimization.js';
import preSendRoutes from './routes/v1/pre-send.js';
import predictiveRoutes from './routes/v1/predictive.js';
import mediaRoutes from './routes/v1/media.js';
import surveyRoutes from './routes/v1/surveys.js';
import zapierRoutes from './routes/v1/zapier.js';
import integrationsCatalogRoutes from './routes/v1/integrations-catalog.js';
import smtpCredentialRoutes from './routes/v1/smtp-credentials.js';
import configurationSetRoutes from './routes/v1/configuration-sets.js';
import emailIdentityRoutes from './routes/v1/email-identities.js';
import inboundRuleRoutes from './routes/v1/inbound-rules.js';
import topicRoutes from './routes/v1/topics.js';
import dataResidencyRoutes from './routes/v1/data-residency.js';
import groupRoutes from './routes/v1/groups.js';
import qrCodeRoutes from './routes/v1/qr-codes.js';
import revenueRoutes from './routes/v1/revenue.js';
import calendarRoutes from './routes/v1/marketing-calendar.js';
import rssRoutes from './routes/v1/rss-campaigns.js';
import transactionalRoutes from './routes/v1/transactional.js';
import twoFactorRoutes from './routes/v1/two-factor.js';
import oauthRoutes from './routes/v1/oauth.js';
import productRoutes from './routes/v1/product-recommendations.js';
import benchmarkRoutes from './routes/v1/benchmarks.js';
import hygieneRoutes from './routes/v1/list-hygiene.js';
import rfmRoutes from './routes/v1/rfm.js';
import smartSendingRoutes from './routes/v1/smart-sending.js';
import quietHoursRoutes from './routes/v1/quiet-hours.js';
import stockAlertRoutes from './routes/v1/stock-alerts.js';
import couponRoutes from './routes/v1/coupons.js';
import reviewRoutes from './routes/v1/reviews.js';
import scheduledReportRoutes from './routes/v1/scheduled-reports.js';
import holdoutRoutes from './routes/v1/holdout.js';
import advancedAnalyticsRoutes from './routes/v1/advanced-analytics.js';
import helpdeskRoutes from './routes/v1/helpdesk.js';
import warehouseSyncRoutes from './routes/v1/warehouse-sync.js';
import smsKeywordRoutes from './routes/v1/sms-keywords.js';
import contactEmailRoutes from './routes/v1/contact-emails.js';
import identityRoutes from './routes/v1/identity.js';
import rcsRoutes from './routes/v1/rcs.js';
import aiAgentRoutes from './routes/v1/ai-agents.js';
import aiRecommendationsRoutes from './routes/v1/ai-recommendations.js';
import multivariateTestsRoutes from './routes/v1/multivariate-tests.js';
import dedicatedIpsRoutes from './routes/v1/dedicated-ips.js';
import abuseDetectionRoutes from './routes/v1/abuse-detection.js';
import ispFeedbackRoutes from './routes/v1/isp-feedback.js';
import ecommerceRoutes from './routes/v1/ecommerce-integrations.js';
import browseAbandonmentRoutes from './routes/v1/browse-abandonment.js';
import inboundEmailRoutes from './routes/v1/inbound-email.js';
import ssoRoutes from './routes/v1/sso.js';
import complianceRoutes from './routes/v1/compliance.js';
import auditLogRoutes from './routes/v1/audit-log.js';
import billingRoutes from './routes/v1/billing.js';
import crmAccountRoutes from './routes/v1/crm/accounts.js';
import crmPipelineRoutes from './routes/v1/crm/pipelines.js';
import crmDealRoutes from './routes/v1/crm/deals.js';
import crmReportRoutes from './routes/v1/crm/reports.js';
import aiSalesRoutes from './routes/v1/ai-sales.js';
import customObjectRoutes from './routes/v1/custom-objects.js';
import salesforceRoutes from './routes/v1/salesforce.js';
import raynetRoutes from './routes/v1/raynet.js';
import productFeedRoutes from './routes/v1/product-feeds.js';
import lifecycleRoutes from './routes/v1/lifecycle.js';
import deliverabilityRoutes from './routes/v1/deliverability.js';
import publicReputationRoutes from './routes/v1/public/reputation.js';
import browserRoutes from './routes/v1/browser.js';
import seoSitemapRoutes from './routes/v1/seo/sitemap.js';
import blogRoutes from './routes/v1/blog.js';
import ctaRoutes from './routes/v1/ctas.js';
import savedQueryRoutes from './routes/v1/saved-queries.js';
import dataSetRoutes from './routes/v1/data-sets.js';
import appStudioRoutes from './routes/v1/app-studio.js';
import crmTaskRoutes from './routes/v1/crm/tasks.js';
import crmNoteRoutes from './routes/v1/crm/notes.js';
import crmActivityRoutes from './routes/v1/crm/activity.js';
import crmSequenceRoutes from './routes/v1/crm/sequences.js';
import siteTrackingRoutes from './routes/v1/site-tracking.js';
import siteMessageRoutes from './routes/v1/site-messages.js';
import webPersonalizationRoutes from './routes/v1/web-personalization.js';
import liveChatRoutes from './routes/v1/helpdesk/live-chat.js';
import universalInboxRoutes from './routes/v1/helpdesk/inbox.js';
import schedulingRoutes from './routes/v1/scheduling.js';
import enrichmentRoutes from './routes/v1/enrichment.js';
import dmarcRoutes from './routes/v1/dmarc.js';
import loyaltyProgramRoutes from './routes/v1/loyalty/programs.js';
import loyaltyRewardRoutes from './routes/v1/loyalty/rewards.js';
import loyaltyEarningRuleRoutes from './routes/v1/loyalty/earning-rules.js';
import loyaltyAnalyticsRoutes from './routes/v1/loyalty/analytics.js';
import loyaltyLedgerRoutes from './routes/v1/loyalty/ledger.js';
import hipaaRoutes from './routes/v1/hipaa.js';
import phoneRoutes from './routes/v1/phone.js';
import calendarSyncRoutes from './routes/v1/calendar.js';
import identityGraphRoutes from './routes/v1/identity-graph.js';
import cdpProfileRoutes from './routes/v1/cdp/profile.js';
import cdpEventRoutes from './routes/v1/cdp/events.js';
import cdpTraitRoutes from './routes/v1/cdp/traits.js';
import cdpActivationRoutes from './routes/v1/cdp/activation.js';
import aiAnalyticsRoutes from './routes/v1/ai-analytics.js';
import hubspotRoutes from './routes/v1/integrations/hubspot.js';
import calendlyRoutes from './routes/v1/integrations/calendly.js';
import instagramWebhookRoutes from './routes/v1/webhooks/instagram.js';
import messengerWebhookRoutes from './routes/v1/webhooks/messenger.js';
import helpdeskRoutingRoutes from './routes/v1/helpdesk/routing.js';
import helpdeskAnalyticsRoutes from './routes/v1/helpdesk/analytics.js';
import aiSupportRoutes from './routes/v1/ai-support.js';
import phoneNumberRoutes from './routes/v1/phone/numbers.js';
import softphoneRoutes from './routes/v1/phone/softphone.js';
import meetingRoutes from './routes/v1/meetings.js';
import cdpSourceRoutes from './routes/v1/cdp/sources.js';
import crossAccountRoutes from './routes/v1/cross-account.js';
import sharedAssetsRoutes from './routes/v1/shared-assets.js';
import billingExtendedRoutes from './routes/v1/billing-extended.js';
import inboxPreviewRoutes from './routes/v1/inbox-preview.js';
import workflowTemplateRoutes from './routes/v1/workflow-templates.js';
import internalArchiveRoutes from './routes/v1/internal/archive.js';
import internalHoldoutRoutes from './routes/v1/internal/holdout.js';
import internalHoldoutBatchRoutes from './routes/v1/internal/holdout-batch.js';
import internalTimewarpRoutes from './routes/v1/internal/timewarp.js';
import internalContactsRoutes from './routes/v1/internal/contacts.js';
import internalSuppressionsRoutes from './routes/v1/internal/suppressions.js';
import internalFrequencyRoutes from './routes/v1/internal/frequency.js';
import internalTrackingDomainRoutes from './routes/v1/internal/tracking-domain.js';
import internalEPrivacyRoutes from './routes/v1/internal/eprivacy.js';
import internalAudienceRoutes from './routes/v1/internal/audience.js';
import internalCouponsRoutes from './routes/v1/internal/coupons.js';
import internalTriggersRoutes from './routes/v1/internal/triggers.js';
import statusPageInternalRoutes from './routes/v1/internal/status-page.js';
import internalChannelScoringRoutes from './routes/v1/internal/channel-scoring.js';
import channelScoringRoutes from './routes/v1/channel-scoring.js';
import internalEngagementScoreRoutes from './routes/v1/internal/engagement-score.js';
import engagementScoreRoutes from './routes/v1/engagement-score.js';
import identityResolutionRoutes from './routes/v1/identity-resolution.js';
import frequencySuppressionsRoutes from './routes/v1/frequency-suppressions.js';
import emailsRoutes from './routes/v1/emails.js';
import aiQuotaRoutes from './routes/v1/ai-quota.js';
import audiencesResendRoutes from './routes/v1/resend-compat/audiences.js';
import broadcastsResendRoutes from './routes/v1/resend-compat/broadcasts.js';
import apiKeysResendRoutes from './routes/v1/resend-compat/api-keys.js';
import domainsResendRoutes from './routes/v1/resend-compat/domains.js';
import dnsHealthRoutes from './routes/v1/dns-health.js';
import anomalyDetectorInternalRoutes from './routes/v1/internal/anomaly-detector.js';
import emailValidationRoutes from './routes/v1/email-validation.js';
import reviewsV2Routes from './routes/v1/reviews-v2.js';
import reportRoutes from './routes/v1/reports.js';
import internalRfmRoutes from './routes/v1/internal/rfm.js';
import internalPredictiveRoutes from './routes/v1/internal/predictive.js';
import internalEventsRoutes from './routes/v1/internal/events.js';
import internalWorkflowDispatchRoutes from './routes/v1/internal/workflow-dispatch.js';
import internalWarehouseSyncRoutes from './routes/v1/internal/warehouse-sync.js';
import internalClickHouseRoutes from './routes/v1/internal/clickhouse.js';
import internalTicketingCronRoutes from './routes/v1/internal/ticketing-cron.js';
import internalBlacklistCheckRoutes from './routes/v1/internal/blacklist-check.js';
import internalNewsletterTiersBatchRoutes from './routes/v1/internal/newsletter-tiers-batch.js';
import newsletterTierRoutes from './routes/v1/newsletter-tiers.js';
import newsletterReferralRoutes from './routes/v1/newsletter-referrals.js';
import bimiRoutes from './routes/v1/bimi.js';
import messagingSendRoutes from './routes/v1/messaging/send.js';
import seoClustersRoutes from './routes/v1/seo/clusters.js';
import seoKeywordsRoutes from './routes/v1/seo/keywords.js';
import seoAuditRoutes from './routes/v1/seo/audit.js';
import seoRankTrackerRoutes from './routes/v1/seo/rank-tracker.js';
import internalSeoRankPollRoutes from './routes/v1/internal/seo-rank-poll.js';
import internalExternalFeedPollRoutes from './routes/v1/internal/external-feeds-poll.js';
import socialAccountRoutes from './routes/v1/social/accounts.js';
import socialPostRoutes from './routes/v1/social/posts.js';
import socialMentionRoutes from './routes/v1/social/mentions.js';
import socialAnalyticsRoutes from './routes/v1/social/analytics.js';
import adAccountRoutes from './routes/v1/ads/accounts.js';
import adAudienceSyncRoutes from './routes/v1/ads/audience-sync.js';
import internalSocialRoutes from './routes/v1/internal/social.js';
import adLookalikeRoutes from './routes/v1/ads/lookalike.js';
import sklikLookalikeRoutes from './routes/v1/ads/sklik-lookalike.js';
import adReportingRoutes from './routes/v1/ads/reporting.js';
import adsWebhookRoutes from './routes/v1/webhooks/ads.js';
import sklikPixelRoutes from './routes/v1/sklik-pixel.js';
import commerceProductRoutes from './routes/v1/commerce/products.js';
import commerceQuoteRoutes from './routes/v1/commerce/quotes.js';
import commerceInvoiceRoutes from './routes/v1/commerce/invoices.js';
import stripeWebhookRoutes from './routes/v1/webhooks/stripe.js';
import commerceSubscriptionRoutes from './routes/v1/commerce/subscriptions.js';
import internalCommerceRoutes from './routes/v1/internal/commerce.js';
import associationRoutes from './routes/v1/associations.js';
import videoRoutes from './routes/v1/video.js';
import ragRoutes from './routes/v1/rag.js';
import i18nRoutes from './routes/v1/i18n.js';
import sandboxRoutes from './routes/v1/sandboxes.js';
import teamRoutes from './routes/v1/teams.js';
import fieldPermissionRoutes from './routes/v1/field-permissions.js';
import customChannelRoutes from './routes/v1/custom-channels.js';
import calcPropRoutes from './routes/v1/calculated-properties.js';
import deliverabilityInsightsRoutes from './routes/v1/deliverability-insights.js';
import dataSyncRoutes from './routes/v1/data-sync.js';
import dataPipelineRoutes from './routes/v1/data-pipelines.js';
import viberRoutes from './routes/v1/viber.js';
import gdprPurposesRoutes from './routes/v1/gdpr/processing-purposes.js';
import gamificationRoutes from './routes/v1/gamification.js';
import socialInboxRoutes from './routes/v1/inbox.js';
import metaWebhookRoutes from './routes/v1/webhooks/meta.js';
import genderRoutes from './routes/v1/gender.js';
import digitalAssetRoutes from './routes/v1/digital-assets.js';
import cannedResponseRoutes from './routes/v1/helpdesk/canned.js';
import workflowExportRoutes from './routes/v1/workflow-export.js';
import cohortAnalyticsRoutes from './routes/v1/cohort-analytics.js';
import surveysNpsRoutes from './routes/v1/surveys-nps.js';
import { externalFeedsRoutes } from './routes/v1/external-feeds.js';
import playbookRoutes from './routes/v1/crm/playbooks.js';
import rotationRoutes from './routes/v1/crm/rotation.js';
import quoteTemplateRoutes from './routes/v1/commerce/quote-templates.js';
import intentSignalRoutes from './routes/v1/intent-signals.js';
import extensionCardRoutes from './routes/v1/crm/extension-cards.js';
import brandVoiceRoutes from './routes/v1/brand-voice.js';
import nbaRoutes from './routes/v1/nba.js';
import attributionRoutes from './routes/v1/attribution.js';
import newsletterAdRoutes from './routes/v1/newsletter-ads.js';
import newsletterAnalyticsRoutes from './routes/v1/newsletter-analytics.js';
import allegroRoutes from './routes/v1/integrations/allegro.js';
import mallCzRoutes from './routes/v1/integrations/mallcz.js';
import personasRoutes from './routes/v1/personas.js';
import zeroPartyDataRoutes from './routes/v1/zero-party-data.js';
import consentGraphRoutes from './routes/v1/consent-graph.js';
import coMarketingRoutes from './routes/v1/co-marketing.js';
import dynamicContentRoutes from './routes/v1/dynamic-content.js';
import competitiveMonitorRoutes from './routes/v1/competitive-monitor.js';
import newsletterPaywallRoutes from './routes/v1/newsletter-paywall.js';
import deliverabilityCoachRoutes from './routes/v1/deliverability-coach.js';
import campaignFatigueRoutes from './routes/v1/campaign-fatigue.js';
import whatIfSimulatorRoutes from './routes/v1/what-if-simulator.js';
import shoptetAdvancedRoutes from './routes/v1/integrations/shoptet-advanced.js';
import brandGuidelinesRoutes from './routes/v1/brand-guidelines.js';
import emailAnnotationsRoutes from './routes/v1/email-annotations.js';
import inboxPlacementRoutes from './routes/v1/inbox-placement.js';
import currencyAnalyticsRoutes from './routes/v1/currency-analytics.js';
import emailThreadRoutes from './routes/v1/email-thread.js';
import crossChannelAttributionRoutes from './routes/v1/cross-channel-attribution.js';
import ticketingRoutes from './routes/v1/ticketing.js';
import partnerRoutes from './routes/v1/partner.js';
import packetaRoutes from './routes/v1/integrations/packeta.js';
import czPaymentRoutes from './routes/v1/integrations/payments-cz.js';
import erpCzRoutes from './routes/v1/integrations/erp-cz.js';
import perContactStoRoutes from './routes/v1/per-contact-sto.js';
import channelFallbackRoutes from './routes/v1/channel-fallback.js';
import aiAltTextRoutes from './routes/v1/ai-alt-text.js';
import unsubscribeAbRoutes from './routes/v1/unsubscribe-ab.js';

export async function buildApp() {
  const app = Fastify({
    logger: {
      level: process.env.LOG_LEVEL || 'info',
      ...(process.env.NODE_ENV !== 'production' && {
        transport: { target: 'pino-pretty' },
      }),
    },
    genReqId: () => crypto.randomUUID(),
    // Honor X-Forwarded-For / X-Forwarded-Proto from upstream proxies
    // (Cloudflare → Coolify → Fastify). Without this, rate-limit
    // keyGenerator sees the proxy IP and treats all traffic as one bucket.
    trustProxy: process.env.NODE_ENV === 'production',
  });

  // Global JSON parser that ALSO preserves the raw request bytes on
  // `req.rawBody`. Webhook routes (Stripe, Meta, ecommerce, billing, phone,
  // custom-channels) must verify provider HMAC signatures against the exact
  // bytes sent — a re-serialized JSON.stringify(req.body) changes whitespace /
  // key order and never matches. Without this, every signature check was either
  // fail-open or permanently failing. parseAs:'buffer' keeps req.body as parsed
  // JSON for ergonomics while exposing the original Buffer for verification.
  app.addContentTypeParser(
    'application/json',
    { parseAs: 'buffer' },
    (req, body, done) => {
      (req as unknown as { rawBody?: Buffer }).rawBody = body as Buffer;
      try {
        const buf = body as Buffer;
        done(null, buf.length ? JSON.parse(buf.toString('utf8')) : {});
      } catch (err) {
        (err as Error & { statusCode?: number }).statusCode = 400;
        done(err as Error, undefined);
      }
    },
  );

  // Plugins (order matters: cookie → auth → routes)
  await app.register(errorHandler);
  await app.register(helmetPlugin);
  await app.register(swaggerPlugin);
  await app.register(corsPlugin);
  await app.register(rateLimitPlugin);
  await app.register(cookiePlugin);
  await app.register(authPlugin);
  await app.register(ipRestrictionsPlugin);
  await app.register(multipartPlugin);
  await app.register(auditPlugin);

  // Routes
  await app.register(healthRoutes);
  await app.register(superadminRoutes);
  await app.register(contactRoutes);
  await app.register(contactImportRoutes);
  await app.register(authRoutes);
  await app.register(segmentRoutes);
  await app.register(frequencyRoutes);
  await app.register(tagRoutes);
  await app.register(customFieldRoutes);
  await app.register(zapierRoutes);
  await app.register(integrationsCatalogRoutes);
  await app.register(smtpCredentialRoutes);
  await app.register(configurationSetRoutes);
  await app.register(emailIdentityRoutes);
  await app.register(inboundRuleRoutes);
  await app.register(topicRoutes);
  await app.register(dataResidencyRoutes);
  await app.register(suppressionRoutes);
  await app.register(subscriptionRoutes);
  await app.register(listRoutes);
  await app.register(organizationRoutes);
  await app.register(aiRoutes);
  await app.register(editorRoutes);
  await app.register(templateRoutes);
  await app.register(domainRoutes);
  await app.register(sendingRoutes);
  await app.register(trackingRoutes);
  await app.register(preferenceCenterRoutes);
  await app.register(consentRoutes);
  await app.register(campaignRoutes);
  await app.register(analyticsRoutes);
  await app.register(statsCategoryRoutes);
  await app.register(mailSettingsRoutes);
  await app.register(seedTestRoutes);
  await app.register(alertRoutes);
  await app.register(workflowRoutes);
  await app.register(eventRoutes);
  await app.register(leadScoringRoutes);
  await app.register(webhookRoutes);
  await app.register(signupFormRoutes);
  await app.register(migrationRoutes);
  await app.register(smsRoutes);
  await app.register(whatsappRoutes);
  await app.register(pushRoutes);
  await app.register(inAppRoutes);
  await app.register(voiceRoutes);
  await app.register(sendOptimizationRoutes);
  await app.register(preSendRoutes);
  await app.register(predictiveRoutes);
  await app.register(mediaRoutes);
  await app.register(surveyRoutes);
  await app.register(groupRoutes);
  await app.register(qrCodeRoutes);
  await app.register(revenueRoutes);
  await app.register(calendarRoutes);
  await app.register(rssRoutes);
  await app.register(transactionalRoutes);
  await app.register(twoFactorRoutes);
  await app.register(oauthRoutes);
  await app.register(productRoutes);
  await app.register(benchmarkRoutes);
  await app.register(hygieneRoutes);
  await app.register(rfmRoutes);
  await app.register(smartSendingRoutes);
  await app.register(quietHoursRoutes);
  await app.register(stockAlertRoutes);
  await app.register(couponRoutes);
  await app.register(reviewRoutes);
  await app.register(scheduledReportRoutes);
  await app.register(holdoutRoutes);
  await app.register(advancedAnalyticsRoutes);
  await app.register(helpdeskRoutes);
  await app.register(warehouseSyncRoutes);
  await app.register(smsKeywordRoutes);
  await app.register(contactEmailRoutes);
  await app.register(identityRoutes);
  await app.register(rcsRoutes);
  await app.register(aiAgentRoutes);
  await app.register(aiRecommendationsRoutes);
  await app.register(multivariateTestsRoutes);
  await app.register(dedicatedIpsRoutes);
  await app.register(abuseDetectionRoutes);
  await app.register(ispFeedbackRoutes);
  await app.register(ecommerceRoutes);
  await app.register(browseAbandonmentRoutes);
  await app.register(inboundEmailRoutes);
  await app.register(ssoRoutes);
  await app.register(complianceRoutes);
  await app.register(auditLogRoutes);
  await app.register(billingRoutes);
  await app.register(crmAccountRoutes);
  await app.register(crmPipelineRoutes);
  await app.register(crmDealRoutes);
  await app.register(crmReportRoutes);
  await app.register(aiSalesRoutes);
  await app.register(customObjectRoutes);
  await app.register(salesforceRoutes);
  await app.register(raynetRoutes);
  await app.register(productFeedRoutes);
  await app.register(lifecycleRoutes);
  await app.register(deliverabilityRoutes);
  await app.register(publicReputationRoutes);
  await app.register(browserRoutes);
  await app.register(seoSitemapRoutes);
  await app.register(blogRoutes);
  await app.register(ctaRoutes);
  await app.register(savedQueryRoutes);
  await app.register(dataSetRoutes);
  await app.register(appStudioRoutes);
  await app.register(crmTaskRoutes);
  await app.register(crmNoteRoutes);
  await app.register(crmActivityRoutes);
  await app.register(crmSequenceRoutes);
  await app.register(siteTrackingRoutes);
  await app.register(siteMessageRoutes);
  await app.register(webPersonalizationRoutes);
  await app.register(liveChatRoutes);
  await app.register(universalInboxRoutes);
  await app.register(schedulingRoutes);
  await app.register(enrichmentRoutes);
  await app.register(dmarcRoutes);
  await app.register(loyaltyProgramRoutes);
  await app.register(loyaltyRewardRoutes);
  await app.register(loyaltyEarningRuleRoutes);
  await app.register(loyaltyAnalyticsRoutes);
  await app.register(loyaltyLedgerRoutes);
  await app.register(hipaaRoutes);
  await app.register(phoneRoutes);
  await app.register(calendarSyncRoutes);
  await app.register(identityGraphRoutes);
  await app.register(cdpProfileRoutes);
  await app.register(cdpEventRoutes);
  await app.register(cdpTraitRoutes);
  await app.register(cdpActivationRoutes);
  await app.register(aiAnalyticsRoutes);
  await app.register(hubspotRoutes);
  await app.register(calendlyRoutes);
  await app.register(instagramWebhookRoutes);
  await app.register(messengerWebhookRoutes);
  await app.register(helpdeskRoutingRoutes);
  await app.register(helpdeskAnalyticsRoutes);
  await app.register(aiSupportRoutes);
  await app.register(phoneNumberRoutes);
  await app.register(softphoneRoutes);
  await app.register(meetingRoutes);
  await app.register(cdpSourceRoutes);
  await app.register(crossAccountRoutes);
  await app.register(sharedAssetsRoutes);
  await app.register(billingExtendedRoutes);
  await app.register(inboxPreviewRoutes);
  await app.register(workflowTemplateRoutes);
  await app.register(internalArchiveRoutes);
  await app.register(internalHoldoutRoutes);
  await app.register(internalHoldoutBatchRoutes);
  await app.register(internalTimewarpRoutes);
  await app.register(internalContactsRoutes);
  await app.register(internalSuppressionsRoutes);
  await app.register(internalFrequencyRoutes);
  await app.register(internalTrackingDomainRoutes);
  await app.register(internalEPrivacyRoutes);
  await app.register(internalAudienceRoutes);
  await app.register(internalCouponsRoutes);
  await app.register(internalTriggersRoutes);
  await app.register(statusPageInternalRoutes);
  await app.register(internalChannelScoringRoutes);
  await app.register(channelScoringRoutes);
  await app.register(internalEngagementScoreRoutes);
  await app.register(engagementScoreRoutes);
  await app.register(identityResolutionRoutes);
  await app.register(frequencySuppressionsRoutes);
  await app.register(emailsRoutes);
  await app.register(aiQuotaRoutes);
  await app.register(audiencesResendRoutes);
  await app.register(broadcastsResendRoutes);
  await app.register(apiKeysResendRoutes);
  await app.register(domainsResendRoutes);
  await app.register(dnsHealthRoutes);
  await app.register(anomalyDetectorInternalRoutes);
  await app.register(emailValidationRoutes);
  await app.register(reviewsV2Routes);
  await app.register(reportRoutes);
  await app.register(internalRfmRoutes);
  await app.register(internalPredictiveRoutes);
  await app.register(internalEventsRoutes);
  await app.register(internalWorkflowDispatchRoutes);
  await app.register(internalWarehouseSyncRoutes);
  await app.register(internalClickHouseRoutes);
  await app.register(internalTicketingCronRoutes);
  await app.register(messagingSendRoutes);
  await app.register(seoClustersRoutes);
  await app.register(seoKeywordsRoutes);
  await app.register(seoAuditRoutes);
  await app.register(seoRankTrackerRoutes);
  await app.register(internalSeoRankPollRoutes);
  await app.register(internalExternalFeedPollRoutes);
  await app.register(socialAccountRoutes);
  await app.register(socialPostRoutes);
  await app.register(socialMentionRoutes);
  await app.register(socialAnalyticsRoutes);
  await app.register(adAccountRoutes);
  await app.register(adAudienceSyncRoutes);
  await app.register(internalSocialRoutes);
  await app.register(adLookalikeRoutes);
  await app.register(sklikLookalikeRoutes);
  await app.register(adReportingRoutes);
  await app.register(adsWebhookRoutes);
  await app.register(sklikPixelRoutes);
  await app.register(commerceProductRoutes);
  await app.register(commerceQuoteRoutes);
  await app.register(commerceInvoiceRoutes);
  await app.register(stripeWebhookRoutes);
  await app.register(commerceSubscriptionRoutes);
  await app.register(internalCommerceRoutes);
  await app.register(associationRoutes);
  await app.register(videoRoutes);
  await app.register(ragRoutes);
  await app.register(i18nRoutes);
  await app.register(sandboxRoutes);
  await app.register(teamRoutes);
  await app.register(fieldPermissionRoutes);
  await app.register(customChannelRoutes);
  await app.register(calcPropRoutes);
  await app.register(deliverabilityInsightsRoutes);
  await app.register(dataSyncRoutes);
  await app.register(dataPipelineRoutes);
  await app.register(viberRoutes);
  await app.register(gdprPurposesRoutes);
  await app.register(gamificationRoutes);
  await app.register(socialInboxRoutes);
  await app.register(metaWebhookRoutes);
  await app.register(genderRoutes);
  await app.register(digitalAssetRoutes);
  await app.register(cannedResponseRoutes);
  await app.register(workflowExportRoutes);
  await app.register(cohortAnalyticsRoutes);
  await app.register(surveysNpsRoutes);
  await app.register(externalFeedsRoutes);
  await app.register(internalBlacklistCheckRoutes);
  await app.register(internalNewsletterTiersBatchRoutes);
  await app.register(newsletterTierRoutes);
  await app.register(newsletterReferralRoutes);
  await app.register(bimiRoutes);
  await app.register(playbookRoutes);
  await app.register(rotationRoutes);
  await app.register(quoteTemplateRoutes);
  await app.register(intentSignalRoutes);
  await app.register(extensionCardRoutes);
  await app.register(brandVoiceRoutes);
  await app.register(nbaRoutes);
  await app.register(attributionRoutes);
  await app.register(newsletterAdRoutes);
  await app.register(newsletterAnalyticsRoutes);
  await app.register(allegroRoutes);
  await app.register(mallCzRoutes);
  await app.register(personasRoutes);
  await app.register(zeroPartyDataRoutes);
  await app.register(consentGraphRoutes);
  await app.register(coMarketingRoutes);
  await app.register(dynamicContentRoutes);
  await app.register(competitiveMonitorRoutes);
  await app.register(newsletterPaywallRoutes);
  await app.register(deliverabilityCoachRoutes);
  await app.register(campaignFatigueRoutes);
  await app.register(whatIfSimulatorRoutes);
  await app.register(shoptetAdvancedRoutes);
  await app.register(brandGuidelinesRoutes);
  await app.register(emailAnnotationsRoutes);
  await app.register(inboxPlacementRoutes);
  await app.register(currencyAnalyticsRoutes);
  await app.register(emailThreadRoutes);
  await app.register(crossChannelAttributionRoutes);
  await app.register(ticketingRoutes);
  await app.register(partnerRoutes);
  await app.register(packetaRoutes);
  await app.register(czPaymentRoutes);
  await app.register(erpCzRoutes);
  await app.register(perContactStoRoutes);
  await app.register(channelFallbackRoutes);
  await app.register(aiAltTextRoutes);
  await app.register(unsubscribeAbRoutes);

  return app;
}

const PORT = Number(process.env.PORT) || 3001;

// Entry-point check. `import.meta.url` is always a URL (`file:///…`) while
// `process.argv[1]` is a platform path, so compare via url.pathToFileURL to
// make this work on both POSIX and Windows.
const entryUrl = (await import('node:url')).pathToFileURL(process.argv[1] ?? '').href;
if (import.meta.url === entryUrl) {
  buildApp()
    .then((app) => app.listen({ port: PORT, host: '0.0.0.0' }))
    .then((address) => {
      console.log(`🚀 API listening on ${address}`);
    })
    .catch((err) => {
      console.error(err);
      process.exit(1);
    });
}
