/**
 * Workflow template registry (Sprint E.3).
 *
 * Templates live in code rather than the DB because:
 *  - they're immutable — no per-org edits, only forks
 *  - shipping them as TS lets us typecheck node configs against NodeType
 *  - new recipes ship with releases; no migration churn
 *
 * Each template is a self-contained recipe with trigger + node graph.
 * Forking copies nodes/edges into a real `workflows` row.
 */

import type { WorkflowNode, WorkflowEdge } from '../../db/schema/workflows.js';

export type TemplateCategory =
  | 'welcome'
  | 'abandoned_cart'
  | 'post_purchase'
  | 'winback'
  | 'birthday'
  | 'browse_abandonment'
  | 'vip_loyalty'
  | 'lead_nurture'
  | 'event'
  | 'feedback_nps'
  | 'cross_sell'
  | 'onboarding'
  | 'churn_prevention'
  | 'date_triggered'
  | 'subscription_renewal'
  | 'transactional'
  | 'review_request'
  | 'replenishment'
  | 'saas_lifecycle'
  | 'sales_engagement'
  | 're_engagement'
  | 'compliance'
  | 'blog_content';

export interface WorkflowTemplate {
  /** Stable URL-safe identifier */
  slug: string;
  name: string;
  category: TemplateCategory;
  description: string;
  /** Audience this template is recommended for (e.g. e-com, B2B SaaS) */
  recommendedFor: string[];
  /** ISO 639-1 base locale ('en', 'cs', 'sk'). Multi-locale forks generate
   *  one workflow per locale at fork time. */
  locale: 'en' | 'cs' | 'sk';
  /** Estimated steps a contact will receive on the happy path */
  steps: number;
  /** Maps to workflow.triggerType + triggerConfig */
  trigger: { type: string; config: Record<string, unknown> };
  nodes: WorkflowNode[];
  edges: WorkflowEdge[];
}

/** Helpers to keep recipe definitions terse. */
const n = (
  id: string,
  type: WorkflowNode['type'],
  config: Record<string, unknown>,
): WorkflowNode => ({ id, type, config });
const e = (id: string, source: string, target: string, label?: string): WorkflowEdge => ({
  id,
  source,
  target,
  label,
});
const wait = (id: string, days: number, hours = 0): WorkflowNode =>
  n(id, 'wait', { duration: { days, hours } });
const email = (id: string, subject: string, templateRef?: string): WorkflowNode =>
  n(id, 'send_email', { subject, templateRef });
const sms = (id: string, body: string): WorkflowNode => n(id, 'send_sms', { body });

export const WORKFLOW_TEMPLATES: WorkflowTemplate[] = [
  // ─── Welcome series ─────────────────────────────────────────────────────────
  {
    slug: 'welcome-3-step-en',
    name: 'Welcome series — 3 emails',
    category: 'welcome',
    description: 'Classic welcome: greeting now, value delivery on day 2, soft offer on day 5.',
    recommendedFor: ['ecommerce', 'saas', 'newsletter'],
    locale: 'en',
    steps: 3,
    trigger: { type: 'list_subscribe', config: {} },
    nodes: [
      n('t', 'trigger', { triggerType: 'list_subscribe' }),
      email('e1', 'Welcome to the family'),
      wait('w1', 2),
      email('e2', "Here's what to do next"),
      wait('w2', 3),
      email('e3', 'A small thank-you gift'),
    ],
    edges: [
      e('e0', 't', 'e1'),
      e('e_e1', 'e1', 'w1'),
      e('e_w1', 'w1', 'e2'),
      e('e_e2', 'e2', 'w2'),
      e('e_w2', 'w2', 'e3'),
    ],
  },
  {
    slug: 'welcome-3-step-cs',
    name: 'Uvítací série — 3 emaily',
    category: 'welcome',
    description: 'Klasická uvítací sekvence v češtině s respektem ke 7 pádům jména.',
    recommendedFor: ['ecommerce', 'saas', 'newsletter'],
    locale: 'cs',
    steps: 3,
    trigger: { type: 'list_subscribe', config: {} },
    nodes: [
      n('t', 'trigger', { triggerType: 'list_subscribe' }),
      email('e1', 'Vítejte mezi námi'),
      wait('w1', 2),
      email('e2', 'Co s námi můžete dělat'),
      wait('w2', 3),
      email('e3', 'Malý dárek na úvod'),
    ],
    edges: [
      e('e0', 't', 'e1'),
      e('e_e1', 'e1', 'w1'),
      e('e_w1', 'w1', 'e2'),
      e('e_e2', 'e2', 'w2'),
      e('e_w2', 'w2', 'e3'),
    ],
  },

  // ─── Abandoned cart ─────────────────────────────────────────────────────────
  {
    slug: 'abandoned-cart-3-touch',
    name: 'Abandoned cart — 3 touches',
    category: 'abandoned_cart',
    description: 'Reminder at 1 hour, urgency at 24 hours, last-chance discount at 72 hours.',
    recommendedFor: ['ecommerce'],
    locale: 'en',
    steps: 3,
    trigger: { type: 'api_event', config: { eventName: 'cart_abandoned' } },
    nodes: [
      n('t', 'trigger', { triggerType: 'api_event', eventName: 'cart_abandoned' }),
      wait('w0', 0, 1),
      email('e1', 'You left something behind'),
      wait('w1', 1),
      email('e2', "Still thinking? Here's a quick reminder"),
      wait('w2', 2),
      email('e3', 'Last chance — 10% off ends tonight'),
    ],
    edges: [
      e('e0', 't', 'w0'),
      e('e1', 'w0', 'e1'),
      e('e2', 'e1', 'w1'),
      e('e3', 'w1', 'e2'),
      e('e4', 'e2', 'w2'),
      e('e5', 'w2', 'e3'),
    ],
  },
  {
    slug: 'abandoned-cart-sms-cascade',
    name: 'Abandoned cart — Email → SMS cascade',
    category: 'abandoned_cart',
    description: 'Email at 1 hour, SMS escalation at 24 hours if cart still abandoned.',
    recommendedFor: ['ecommerce'],
    locale: 'en',
    steps: 2,
    trigger: { type: 'api_event', config: { eventName: 'cart_abandoned' } },
    nodes: [
      n('t', 'trigger', { triggerType: 'api_event', eventName: 'cart_abandoned' }),
      wait('w0', 0, 1),
      email('e1', 'You left something in your cart'),
      wait('w1', 1),
      n('c1', 'condition', { rule: { type: 'cart_still_abandoned' } }),
      n('s1', 'send_sms', { body: 'Your cart is waiting — finish checkout: {{cart.url}}' }),
    ],
    edges: [
      e('e0', 't', 'w0'),
      e('e1', 'w0', 'e1'),
      e('e2', 'e1', 'w1'),
      e('e3', 'w1', 'c1'),
      e('e4', 'c1', 's1', 'true'),
    ],
  },

  // ─── Post-purchase ──────────────────────────────────────────────────────────
  {
    slug: 'post-purchase-thanks-review',
    name: 'Post-purchase: Thanks + Review request',
    category: 'post_purchase',
    description: 'Thank-you within an hour, shipping prep day 2, review ask 10 days after.',
    recommendedFor: ['ecommerce'],
    locale: 'en',
    steps: 3,
    trigger: { type: 'purchase_event', config: {} },
    nodes: [
      n('t', 'trigger', { triggerType: 'purchase_event' }),
      email('e1', 'Thanks for your order!'),
      wait('w1', 1),
      email('e2', 'Your order is on its way'),
      wait('w2', 10),
      email('e3', 'How was your order?'),
    ],
    edges: [
      e('e0', 't', 'e1'),
      e('e1', 'e1', 'w1'),
      e('e2', 'w1', 'e2'),
      e('e3', 'e2', 'w2'),
      e('e4', 'w2', 'e3'),
    ],
  },

  // ─── Win-back ───────────────────────────────────────────────────────────────
  {
    slug: 'winback-90-day',
    name: 'Win-back — 90 days inactive',
    category: 'winback',
    description: 'Gentle re-engagement after 90 days of no opens. Two emails plus a sunset offer.',
    recommendedFor: ['newsletter', 'ecommerce'],
    locale: 'en',
    steps: 3,
    trigger: { type: 'date_field', config: { field: 'last_open_at', daysSince: 90 } },
    nodes: [
      n('t', 'trigger', { triggerType: 'date_field', field: 'last_open_at', daysSince: 90 }),
      email('e1', 'We miss you'),
      wait('w1', 7),
      n('c1', 'condition', { rule: { type: 'opened_email_within', days: 7 } }),
      email('e2', '20% off if you come back this week'),
      wait('w2', 14),
      n('s1', 'move_to_list', { listSlug: 'sunset' }),
    ],
    edges: [
      e('e0', 't', 'e1'),
      e('e1', 'e1', 'w1'),
      e('e2', 'w1', 'c1'),
      e('e3', 'c1', 'e2', 'false'),
      e('e4', 'e2', 'w2'),
      e('e5', 'w2', 's1'),
    ],
  },

  // ─── Birthday ───────────────────────────────────────────────────────────────
  {
    slug: 'birthday-discount',
    name: 'Birthday discount',
    category: 'birthday',
    description: "Send a 15% discount code on the contact's birthday (3 days before for reminder).",
    recommendedFor: ['ecommerce', 'fitness', 'beauty'],
    locale: 'en',
    steps: 2,
    trigger: { type: 'date_field', config: { field: 'birthday', daysBefore: 3 } },
    nodes: [
      n('t', 'trigger', { triggerType: 'date_field', field: 'birthday', daysBefore: 3 }),
      email('e1', "Happy birthday week — here's 15% off"),
      wait('w1', 3),
      email('e2', 'Today is your day!'),
    ],
    edges: [e('e0', 't', 'e1'), e('e1', 'e1', 'w1'), e('e2', 'w1', 'e2')],
  },

  // ─── Browse abandonment ─────────────────────────────────────────────────────
  {
    slug: 'browse-abandonment-2-touch',
    name: 'Browse abandonment — 2 touches',
    category: 'browse_abandonment',
    description: 'Triggered when contact viewed product 3+ times without purchase.',
    recommendedFor: ['ecommerce'],
    locale: 'en',
    steps: 2,
    trigger: { type: 'api_event', config: { eventName: 'product_viewed_3x' } },
    nodes: [
      n('t', 'trigger', { triggerType: 'api_event', eventName: 'product_viewed_3x' }),
      wait('w0', 0, 4),
      email('e1', 'Still interested in {{product.name}}?'),
      wait('w1', 2),
      email('e2', 'Reviews from people who bought {{product.name}}'),
    ],
    edges: [e('e0', 't', 'w0'), e('e1', 'w0', 'e1'), e('e2', 'e1', 'w1'), e('e3', 'w1', 'e2')],
  },

  // ─── VIP / loyalty ──────────────────────────────────────────────────────────
  {
    slug: 'vip-tier-upgrade',
    name: 'VIP — Loyalty tier upgrade',
    category: 'vip_loyalty',
    description: 'Welcome the contact to their new VIP tier with perks summary.',
    recommendedFor: ['ecommerce', 'saas'],
    locale: 'en',
    steps: 2,
    trigger: { type: 'loyalty_tier_up', config: {} },
    nodes: [
      n('t', 'trigger', { triggerType: 'loyalty_tier_up' }),
      email('e1', 'Welcome to {{loyalty.tier}}'),
      wait('w1', 7),
      email('e2', 'Try your new {{loyalty.tier}} perks'),
    ],
    edges: [e('e0', 't', 'e1'), e('e1', 'e1', 'w1'), e('e2', 'w1', 'e2')],
  },

  // ─── Lead nurture (B2B) ─────────────────────────────────────────────────────
  {
    slug: 'lead-nurture-saas-trial',
    name: 'SaaS trial nurture — 14 days',
    category: 'lead_nurture',
    description:
      '5-touch nurture for a 14-day SaaS trial: onboarding, value, social proof, ROI, conversion ask.',
    recommendedFor: ['saas', 'b2b'],
    locale: 'en',
    steps: 5,
    trigger: { type: 'api_event', config: { eventName: 'trial_started' } },
    nodes: [
      n('t', 'trigger', { triggerType: 'api_event', eventName: 'trial_started' }),
      email('e1', "Welcome — let's get you set up"),
      wait('w1', 2),
      email('e2', 'How customers use {{product.name}}'),
      wait('w2', 3),
      email('e3', 'Case study: 40% productivity gain'),
      wait('w3', 4),
      email('e4', 'Your ROI calculator'),
      wait('w4', 4),
      email('e5', "Ready to upgrade? Here's 20% off your first month"),
    ],
    edges: [
      e('e0', 't', 'e1'),
      e('e1', 'e1', 'w1'),
      e('e2', 'w1', 'e2'),
      e('e3', 'e2', 'w2'),
      e('e4', 'w2', 'e3'),
      e('e5', 'e3', 'w3'),
      e('e6', 'w3', 'e4'),
      e('e7', 'e4', 'w4'),
      e('e8', 'w4', 'e5'),
    ],
  },

  // ─── Event ──────────────────────────────────────────────────────────────────
  {
    slug: 'event-webinar-reminder',
    name: 'Webinar registration reminder',
    category: 'event',
    description: 'Confirmation, day-before reminder, hour-before reminder, post-event recap.',
    recommendedFor: ['saas', 'b2b', 'events'],
    locale: 'en',
    steps: 4,
    trigger: { type: 'form_submit', config: { formSlug: 'webinar-registration' } },
    nodes: [
      n('t', 'trigger', { triggerType: 'form_submit', formSlug: 'webinar-registration' }),
      email('e1', "You're registered: {{event.name}}"),
      n('w1', 'wait', { until: { field: 'event.starts_at', offsetHours: -24 } }),
      email('e2', 'Tomorrow: {{event.name}}'),
      n('w2', 'wait', { until: { field: 'event.starts_at', offsetHours: -1 } }),
      email('e3', 'Starting in 1 hour'),
      n('w3', 'wait', { until: { field: 'event.starts_at', offsetHours: 24 } }),
      email('e4', 'Recording + slides from {{event.name}}'),
    ],
    edges: [
      e('e0', 't', 'e1'),
      e('e1', 'e1', 'w1'),
      e('e2', 'w1', 'e2'),
      e('e3', 'e2', 'w2'),
      e('e4', 'w2', 'e3'),
      e('e5', 'e3', 'w3'),
      e('e6', 'w3', 'e4'),
    ],
  },

  // ─── Feedback / NPS ─────────────────────────────────────────────────────────
  {
    slug: 'nps-survey-30-day',
    name: 'NPS survey — 30 days post-purchase',
    category: 'feedback_nps',
    description:
      'Single-question NPS at 30 days post-purchase, branched follow-up for promoters vs detractors.',
    recommendedFor: ['ecommerce', 'saas'],
    locale: 'en',
    steps: 2,
    trigger: { type: 'date_field', config: { field: 'first_order_at', daysAfter: 30 } },
    nodes: [
      n('t', 'trigger', { triggerType: 'date_field', field: 'first_order_at', daysAfter: 30 }),
      email('e1', 'How likely are you to recommend us?'),
      wait('w1', 5),
      n('c1', 'condition', { rule: { type: 'nps_score_gte', value: 9 } }),
      email('e2', 'Thanks! Could you leave a public review?'),
      email('e3', "We'd love to make it right — quick reply?"),
    ],
    edges: [
      e('e0', 't', 'e1'),
      e('e1', 'e1', 'w1'),
      e('e2', 'w1', 'c1'),
      e('e3', 'c1', 'e2', 'true'),
      e('e4', 'c1', 'e3', 'false'),
    ],
  },

  // ─── Cross-sell ────────────────────────────────────────────────────────────
  {
    slug: 'cross-sell-related-products',
    name: 'Cross-sell — Related products 14 days post-purchase',
    category: 'cross_sell',
    description: 'Recommends related products 14 days after first purchase based on category.',
    recommendedFor: ['ecommerce'],
    locale: 'en',
    steps: 1,
    trigger: { type: 'purchase_event', config: {} },
    nodes: [
      n('t', 'trigger', { triggerType: 'purchase_event' }),
      wait('w1', 14),
      email('e1', 'You might also love these'),
    ],
    edges: [e('e0', 't', 'w1'), e('e1', 'w1', 'e1')],
  },

  // ─── Onboarding ────────────────────────────────────────────────────────────
  {
    slug: 'onboarding-saas-7-day',
    name: 'SaaS product onboarding — 7 days',
    category: 'onboarding',
    description: 'Activation-focused onboarding nudges based on feature usage.',
    recommendedFor: ['saas'],
    locale: 'en',
    steps: 4,
    trigger: { type: 'api_event', config: { eventName: 'signup_completed' } },
    nodes: [
      n('t', 'trigger', { triggerType: 'api_event', eventName: 'signup_completed' }),
      email('e1', 'Step 1: Invite your team'),
      wait('w1', 1),
      n('c1', 'condition', { rule: { type: 'feature_used', feature: 'team_invite' } }),
      email('e2', 'Step 2: Connect your data source'),
      wait('w2', 2),
      email('e3', 'Step 3: Set up your first automation'),
      wait('w3', 3),
      email('e4', "You're a power user now — here's what advanced users do"),
    ],
    edges: [
      e('e0', 't', 'e1'),
      e('e1', 'e1', 'w1'),
      e('e2', 'w1', 'c1'),
      e('e3', 'c1', 'e2', 'false'),
      e('e4', 'e2', 'w2'),
      e('e5', 'w2', 'e3'),
      e('e6', 'e3', 'w3'),
      e('e7', 'w3', 'e4'),
    ],
  },

  // ─── Churn prevention ──────────────────────────────────────────────────────
  {
    slug: 'churn-prevention-high-risk',
    name: 'Churn prevention — high-risk contacts',
    category: 'churn_prevention',
    description: 'Triggers when churn_risk crosses 0.7. Outreach email + manual rep follow-up.',
    recommendedFor: ['saas', 'subscription'],
    locale: 'en',
    steps: 2,
    trigger: { type: 'api_event', config: { eventName: 'churn_risk_high' } },
    nodes: [
      n('t', 'trigger', { triggerType: 'api_event', eventName: 'churn_risk_high' }),
      email('e1', 'Anything we can help with?'),
      wait('w1', 3),
      n('a1', 'assign_task', { taskType: 'churn-rescue-call' }),
    ],
    edges: [e('e0', 't', 'e1'), e('e1', 'e1', 'w1'), e('e2', 'w1', 'a1')],
  },

  // ─── Date-triggered (CZ jmeniny) ───────────────────────────────────────────
  {
    slug: 'cz-name-day-greeting',
    name: 'CZ jmeniny — name day greeting',
    category: 'date_triggered',
    description:
      "Sends a greeting on the contact's CZ name day (svátek). Auto-personalized 1st-name vocative.",
    recommendedFor: ['ecommerce', 'fitness', 'cz-sk-saas'],
    locale: 'cs',
    steps: 1,
    trigger: { type: 'name_day_today', config: {} },
    nodes: [
      n('t', 'trigger', { triggerType: 'name_day_today' }),
      email('e1', 'Vše nejlepší k svátku, {{contact.first_name|vocative}}!'),
    ],
    edges: [e('e0', 't', 'e1')],
  },
  {
    slug: 'cz-holiday-easter-week',
    name: 'CZ Velikonoce — týden před',
    category: 'date_triggered',
    description: 'Promotional email 7 days before Easter Monday (CZ public holiday).',
    recommendedFor: ['ecommerce', 'cz-sk'],
    locale: 'cs',
    steps: 1,
    trigger: { type: 'n_days_before_holiday', config: { holiday: 'easter_monday', daysBefore: 7 } },
    nodes: [
      n('t', 'trigger', {
        triggerType: 'n_days_before_holiday',
        holiday: 'easter_monday',
        daysBefore: 7,
      }),
      email('e1', 'Velikonoční nabídka — slevy do 30 %'),
    ],
    edges: [e('e0', 't', 'e1')],
  },

  // ─── Subscription renewal ──────────────────────────────────────────────────
  {
    slug: 'subscription-renewal-30-7-1',
    name: 'Subscription renewal — 30/7/1 day cadence',
    category: 'subscription_renewal',
    description: 'Renewal reminders at T-30, T-7, T-1 days before billing.',
    recommendedFor: ['saas', 'subscription'],
    locale: 'en',
    steps: 3,
    trigger: { type: 'date_field', config: { field: 'subscription_renews_at', daysBefore: 30 } },
    nodes: [
      n('t', 'trigger', {
        triggerType: 'date_field',
        field: 'subscription_renews_at',
        daysBefore: 30,
      }),
      email('e1', 'Your subscription renews in 30 days'),
      wait('w1', 23),
      email('e2', 'Your subscription renews in 7 days'),
      wait('w2', 6),
      email('e3', 'Tomorrow: your subscription renews'),
    ],
    edges: [
      e('e0', 't', 'e1'),
      e('e1', 'e1', 'w1'),
      e('e2', 'w1', 'e2'),
      e('e3', 'e2', 'w2'),
      e('e4', 'w2', 'e3'),
    ],
  },

  // ─── Welcome variants ──────────────────────────────────────────────────────
  {
    slug: 'welcome-5-step-en',
    name: 'Welcome series — 5 emails',
    category: 'welcome',
    description: 'Extended onboarding: welcome, value, social proof, education, soft offer.',
    recommendedFor: ['ecommerce', 'saas', 'newsletter'],
    locale: 'en',
    steps: 5,
    trigger: { type: 'list_subscribe', config: {} },
    nodes: [
      n('t', 'trigger', { triggerType: 'list_subscribe' }),
      email('e1', 'Welcome — here is what to expect'),
      wait('w1', 1),
      email('e2', 'Our story in 2 minutes'),
      wait('w2', 2),
      email('e3', 'Reviews from real customers'),
      wait('w3', 3),
      email('e4', 'A guide to getting the most from us'),
      wait('w4', 4),
      email('e5', 'Special offer for new subscribers'),
    ],
    edges: [
      e('e0', 't', 'e1'),
      e('e1', 'e1', 'w1'),
      e('e2', 'w1', 'e2'),
      e('e3', 'e2', 'w2'),
      e('e4', 'w2', 'e3'),
      e('e5', 'e3', 'w3'),
      e('e6', 'w3', 'e4'),
      e('e7', 'e4', 'w4'),
      e('e8', 'w4', 'e5'),
    ],
  },
  {
    slug: 'welcome-3-step-sk',
    name: 'Uvítacia séria — 3 emaily',
    category: 'welcome',
    description: 'Slovenská uvítacia séria s podporou skloňovania mena (vokatív).',
    recommendedFor: ['ecommerce', 'saas', 'newsletter'],
    locale: 'sk',
    steps: 3,
    trigger: { type: 'list_subscribe', config: {} },
    nodes: [
      n('t', 'trigger', { triggerType: 'list_subscribe' }),
      email('e1', 'Vitajte u nás'),
      wait('w1', 2),
      email('e2', 'Čo s nami môžete robiť'),
      wait('w2', 3),
      email('e3', 'Malý darček na úvod'),
    ],
    edges: [
      e('e0', 't', 'e1'),
      e('e1', 'e1', 'w1'),
      e('e2', 'w1', 'e2'),
      e('e3', 'e2', 'w2'),
      e('e4', 'w2', 'e3'),
    ],
  },
  {
    slug: 'welcome-discount-magnet',
    name: 'Welcome — Discount on subscribe',
    category: 'welcome',
    description: 'Lead magnet flow: 10% off code on subscribe, value email day 2, urgency day 4.',
    recommendedFor: ['ecommerce', 'fashion', 'beauty'],
    locale: 'en',
    steps: 3,
    trigger: { type: 'list_subscribe', config: { source: 'popup-newsletter' } },
    nodes: [
      n('t', 'trigger', { triggerType: 'list_subscribe' }),
      email('e1', 'Your 10% welcome code: WELCOME10'),
      wait('w1', 2),
      email('e2', 'Bestsellers our community loves'),
      wait('w2', 2),
      email('e3', 'Last day to use WELCOME10'),
    ],
    edges: [
      e('e0', 't', 'e1'),
      e('e1', 'e1', 'w1'),
      e('e2', 'w1', 'e2'),
      e('e3', 'e2', 'w2'),
      e('e4', 'w2', 'e3'),
    ],
  },

  // ─── Abandoned cart variants ──────────────────────────────────────────────
  {
    slug: 'abandoned-cart-discount-escalation',
    name: 'Abandoned cart — discount escalation',
    category: 'abandoned_cart',
    description: 'No discount, then 10%, then 20% over three touches.',
    recommendedFor: ['ecommerce'],
    locale: 'en',
    steps: 3,
    trigger: { type: 'api_event', config: { eventName: 'cart_abandoned' } },
    nodes: [
      n('t', 'trigger', { triggerType: 'api_event', eventName: 'cart_abandoned' }),
      wait('w0', 0, 1),
      email('e1', 'Forgetting something?'),
      wait('w1', 1),
      email('e2', '10% off your cart — code BACK10'),
      wait('w2', 2),
      email('e3', 'Final offer: 20% off — code BACK20'),
    ],
    edges: [
      e('e0', 't', 'w0'),
      e('e1', 'w0', 'e1'),
      e('e2', 'e1', 'w1'),
      e('e3', 'w1', 'e2'),
      e('e4', 'e2', 'w2'),
      e('e5', 'w2', 'e3'),
    ],
  },
  {
    slug: 'abandoned-cart-cs',
    name: 'Opuštěný košík — 3 doteky',
    category: 'abandoned_cart',
    description: 'Připomenutí v hodinách a dnech, s respektem ke 7 pádům jména v češtině.',
    recommendedFor: ['ecommerce'],
    locale: 'cs',
    steps: 3,
    trigger: { type: 'api_event', config: { eventName: 'cart_abandoned' } },
    nodes: [
      n('t', 'trigger', { triggerType: 'api_event', eventName: 'cart_abandoned' }),
      wait('w0', 0, 1),
      email('e1', 'Něco vám zůstalo v košíku'),
      wait('w1', 1),
      email('e2', 'Vaše položky čekají'),
      wait('w2', 2),
      email('e3', 'Poslední šance — sleva 10 %'),
    ],
    edges: [
      e('e0', 't', 'w0'),
      e('e1', 'w0', 'e1'),
      e('e2', 'e1', 'w1'),
      e('e3', 'w1', 'e2'),
      e('e4', 'e2', 'w2'),
      e('e5', 'w2', 'e3'),
    ],
  },
  {
    slug: 'abandoned-cart-high-value',
    name: 'Abandoned cart — high-value with rep',
    category: 'abandoned_cart',
    description: 'For carts above a threshold: 1-hour email + sales rep task at 24 hours.',
    recommendedFor: ['ecommerce', 'b2b'],
    locale: 'en',
    steps: 2,
    trigger: { type: 'api_event', config: { eventName: 'cart_abandoned', minValue: 250 } },
    nodes: [
      n('t', 'trigger', { triggerType: 'api_event', eventName: 'cart_abandoned' }),
      n('c1', 'condition', { rule: { type: 'cart_value_gte', value: 250 } }),
      wait('w1', 0, 1),
      email('e1', 'Need help finishing your order?'),
      wait('w2', 1),
      n('a1', 'assign_task', { taskType: 'high-value-cart-callback' }),
    ],
    edges: [
      e('e0', 't', 'c1'),
      e('e1', 'c1', 'w1', 'true'),
      e('e2', 'w1', 'e1'),
      e('e3', 'e1', 'w2'),
      e('e4', 'w2', 'a1'),
    ],
  },

  // ─── Post-purchase variants ───────────────────────────────────────────────
  {
    slug: 'post-purchase-shipping-update',
    name: 'Post-purchase: Shipping tracker',
    category: 'post_purchase',
    description: 'Order confirmation, packed, shipped, delivered touchpoints.',
    recommendedFor: ['ecommerce'],
    locale: 'en',
    steps: 4,
    trigger: { type: 'purchase_event', config: {} },
    nodes: [
      n('t', 'trigger', { triggerType: 'purchase_event' }),
      email('e1', 'Order #{{order.id}} confirmed'),
      n('w1', 'wait', { until: { event: 'order_packed' } }),
      email('e2', 'Your order is packed'),
      n('w2', 'wait', { until: { event: 'order_shipped' } }),
      email('e3', 'Your order has shipped — track it here'),
      n('w3', 'wait', { until: { event: 'order_delivered' } }),
      email('e4', 'Your order arrived — enjoy!'),
    ],
    edges: [
      e('e0', 't', 'e1'),
      e('e1', 'e1', 'w1'),
      e('e2', 'w1', 'e2'),
      e('e3', 'e2', 'w2'),
      e('e4', 'w2', 'e3'),
      e('e5', 'e3', 'w3'),
      e('e6', 'w3', 'e4'),
    ],
  },
  {
    slug: 'post-purchase-bundle-upsell',
    name: 'Post-purchase: Bundle upsell',
    category: 'post_purchase',
    description: 'Day 3 — recommend a complementary product as a discounted bundle.',
    recommendedFor: ['ecommerce'],
    locale: 'en',
    steps: 1,
    trigger: { type: 'purchase_event', config: {} },
    nodes: [
      n('t', 'trigger', { triggerType: 'purchase_event' }),
      wait('w1', 3),
      email('e1', 'Complete the set — save 15% on the bundle'),
    ],
    edges: [e('e0', 't', 'w1'), e('e1', 'w1', 'e1')],
  },

  // ─── Replenishment ────────────────────────────────────────────────────────
  {
    slug: 'replenishment-30-day',
    name: 'Replenishment reminder — 30 days',
    category: 'replenishment',
    description: 'For consumables: reminder at 25 days, follow-up at 32 days.',
    recommendedFor: ['ecommerce', 'beauty', 'pet'],
    locale: 'en',
    steps: 2,
    trigger: { type: 'purchase_event', config: { categoryTag: 'consumable' } },
    nodes: [
      n('t', 'trigger', { triggerType: 'purchase_event' }),
      wait('w1', 25),
      email('e1', 'Running low? Reorder in one click'),
      wait('w2', 7),
      n('c1', 'condition', { rule: { type: 'reordered_within', days: 7 } }),
      email('e2', "It's been a month — time for a refill?"),
    ],
    edges: [
      e('e0', 't', 'w1'),
      e('e1', 'w1', 'e1'),
      e('e2', 'e1', 'w2'),
      e('e3', 'w2', 'c1'),
      e('e4', 'c1', 'e2', 'false'),
    ],
  },
  {
    slug: 'replenishment-90-day',
    name: 'Replenishment reminder — 90 days',
    category: 'replenishment',
    description: 'For long-cycle consumables: reminder at 80 days plus auto-refill CTA.',
    recommendedFor: ['ecommerce', 'pet', 'wellness'],
    locale: 'en',
    steps: 1,
    trigger: { type: 'purchase_event', config: { categoryTag: 'long-cycle' } },
    nodes: [
      n('t', 'trigger', { triggerType: 'purchase_event' }),
      wait('w1', 80),
      email('e1', 'Time to restock — set up auto-refill?'),
    ],
    edges: [e('e0', 't', 'w1'), e('e1', 'w1', 'e1')],
  },

  // ─── Winback variants ─────────────────────────────────────────────────────
  {
    slug: 'winback-60-day',
    name: 'Win-back — 60 days inactive',
    category: 'winback',
    description: 'Earlier touchpoint than the 90-day flow — softer ask, no discount yet.',
    recommendedFor: ['newsletter', 'ecommerce'],
    locale: 'en',
    steps: 2,
    trigger: { type: 'date_field', config: { field: 'last_open_at', daysSince: 60 } },
    nodes: [
      n('t', 'trigger', { triggerType: 'date_field', field: 'last_open_at', daysSince: 60 }),
      email('e1', 'Did we lose touch?'),
      wait('w1', 5),
      email('e2', "Here's what's new since you've been away"),
    ],
    edges: [e('e0', 't', 'e1'), e('e1', 'e1', 'w1'), e('e2', 'w1', 'e2')],
  },
  {
    slug: 'winback-vip-rescue',
    name: 'Win-back — VIP rescue',
    category: 'winback',
    description: 'High-CLV contact inactive: personal email + sales rep call task.',
    recommendedFor: ['ecommerce', 'b2b'],
    locale: 'en',
    steps: 2,
    trigger: { type: 'api_event', config: { eventName: 'vip_inactive_30d' } },
    nodes: [
      n('t', 'trigger', { triggerType: 'api_event', eventName: 'vip_inactive_30d' }),
      n('p1', 'send_personal_email', { subject: 'Personal note from your account manager' }),
      wait('w1', 3),
      n('a1', 'assign_task', { taskType: 'vip-checkin-call' }),
    ],
    edges: [e('e0', 't', 'p1'), e('e1', 'p1', 'w1'), e('e2', 'w1', 'a1')],
  },

  // ─── Birthday CS ──────────────────────────────────────────────────────────
  {
    slug: 'birthday-cs',
    name: 'Narozeninová sleva',
    category: 'birthday',
    description: 'Sleva 15 % v týdnu narozenin, hlavní den extra připomenutí.',
    recommendedFor: ['ecommerce', 'fitness'],
    locale: 'cs',
    steps: 2,
    trigger: { type: 'date_field', config: { field: 'birthday', daysBefore: 3 } },
    nodes: [
      n('t', 'trigger', { triggerType: 'date_field', field: 'birthday', daysBefore: 3 }),
      email('e1', 'Narozeninový týden — 15 % sleva pro vás'),
      wait('w1', 3),
      email('e2', 'Vše nejlepší!'),
    ],
    edges: [e('e0', 't', 'e1'), e('e1', 'e1', 'w1'), e('e2', 'w1', 'e2')],
  },

  // ─── Browse abandonment — price drop ──────────────────────────────────────
  {
    slug: 'browse-abandonment-price-drop',
    name: 'Browse abandonment — Price drop alert',
    category: 'browse_abandonment',
    description: 'Triggers when a previously viewed product drops in price by ≥10%.',
    recommendedFor: ['ecommerce'],
    locale: 'en',
    steps: 1,
    trigger: { type: 'api_event', config: { eventName: 'viewed_product_price_dropped' } },
    nodes: [
      n('t', 'trigger', { triggerType: 'api_event', eventName: 'viewed_product_price_dropped' }),
      email('e1', '{{product.name}} just dropped {{product.discountPct}}%'),
    ],
    edges: [e('e0', 't', 'e1')],
  },

  // ─── Loyalty events ───────────────────────────────────────────────────────
  {
    slug: 'loyalty-points-earned-thanks',
    name: 'Loyalty — Points earned thank-you',
    category: 'vip_loyalty',
    description: 'Fires whenever a member earns points — summarises balance and next reward.',
    recommendedFor: ['ecommerce', 'saas'],
    locale: 'en',
    steps: 1,
    trigger: { type: 'loyalty_points_earned', config: {} },
    nodes: [
      n('t', 'trigger', { triggerType: 'loyalty_points_earned' }),
      email('e1', 'You earned {{loyalty.delta}} points — balance {{loyalty.balance}}'),
    ],
    edges: [e('e0', 't', 'e1')],
  },
  {
    slug: 'loyalty-reward-redeemed-confirm',
    name: 'Loyalty — Reward redeemed confirmation',
    category: 'vip_loyalty',
    description: 'Confirmation + delivery instructions when a reward is redeemed.',
    recommendedFor: ['ecommerce'],
    locale: 'en',
    steps: 1,
    trigger: { type: 'loyalty_reward_redeemed', config: {} },
    nodes: [
      n('t', 'trigger', { triggerType: 'loyalty_reward_redeemed' }),
      email('e1', 'Your reward {{reward.name}} is on the way'),
    ],
    edges: [e('e0', 't', 'e1')],
  },
  {
    slug: 'loyalty-points-expiring',
    name: 'Loyalty — Points expiring soon',
    category: 'vip_loyalty',
    description: 'Warning 30 days before unused points expire so the member redeems.',
    recommendedFor: ['ecommerce'],
    locale: 'en',
    steps: 1,
    trigger: { type: 'date_field', config: { field: 'loyalty.points_expire_at', daysBefore: 30 } },
    nodes: [
      n('t', 'trigger', {
        triggerType: 'date_field',
        field: 'loyalty.points_expire_at',
        daysBefore: 30,
      }),
      email('e1', '{{loyalty.balance}} points expire in 30 days — redeem now'),
    ],
    edges: [e('e0', 't', 'e1')],
  },

  // ─── Lead nurture B2B variants ────────────────────────────────────────────
  {
    slug: 'lead-nurture-content-download',
    name: 'B2B — Content download follow-up',
    category: 'lead_nurture',
    description: 'Asset delivery + 3-touch nurture sequence after a whitepaper download.',
    recommendedFor: ['b2b', 'saas'],
    locale: 'en',
    steps: 4,
    trigger: { type: 'form_submit', config: { formSlug: 'whitepaper-download' } },
    nodes: [
      n('t', 'trigger', { triggerType: 'form_submit', formSlug: 'whitepaper-download' }),
      email('e1', "Here's your whitepaper"),
      wait('w1', 2),
      email('e2', '3 questions our whitepaper answers'),
      wait('w2', 3),
      email('e3', 'Case study: how teams apply this'),
      wait('w3', 4),
      email('e4', 'Talk to our team — 15-min walkthrough'),
    ],
    edges: [
      e('e0', 't', 'e1'),
      e('e1', 'e1', 'w1'),
      e('e2', 'w1', 'e2'),
      e('e3', 'e2', 'w2'),
      e('e4', 'w2', 'e3'),
      e('e5', 'e3', 'w3'),
      e('e6', 'w3', 'e4'),
    ],
  },
  {
    slug: 'lead-nurture-demo-followup',
    name: 'B2B — Post-demo follow-up',
    category: 'lead_nurture',
    description: 'Recap + decision-maker proof + procurement-friendly assets within a week.',
    recommendedFor: ['b2b', 'saas'],
    locale: 'en',
    steps: 3,
    trigger: { type: 'api_event', config: { eventName: 'demo_completed' } },
    nodes: [
      n('t', 'trigger', { triggerType: 'api_event', eventName: 'demo_completed' }),
      wait('w0', 0, 2),
      email('e1', 'Thanks for your time — recap + recording'),
      wait('w1', 2),
      email('e2', 'Why teams choose us over alternatives'),
      wait('w2', 3),
      email('e3', 'Pricing and security overview for procurement'),
    ],
    edges: [
      e('e0', 't', 'w0'),
      e('e1', 'w0', 'e1'),
      e('e2', 'e1', 'w1'),
      e('e3', 'w1', 'e2'),
      e('e4', 'e2', 'w2'),
      e('e5', 'w2', 'e3'),
    ],
  },
  {
    slug: 'lead-nurture-mql-handoff',
    name: 'B2B — MQL to SQL handoff',
    category: 'lead_nurture',
    description: 'MQL hit lead-score threshold: route to AE, schedule task, send intro email.',
    recommendedFor: ['b2b', 'saas'],
    locale: 'en',
    steps: 1,
    trigger: { type: 'api_event', config: { eventName: 'lead_qualified_marketing' } },
    nodes: [
      n('t', 'trigger', { triggerType: 'api_event', eventName: 'lead_qualified_marketing' }),
      n('a1', 'assign_task', { taskType: 'mql-discovery-call', roundRobin: true }),
      email('e1', "We'd love to chat — choose a time"),
    ],
    edges: [e('e0', 't', 'a1'), e('e1', 'a1', 'e1')],
  },

  // ─── Event variants ───────────────────────────────────────────────────────
  {
    slug: 'event-in-person-prep',
    name: 'In-person event — prep + day-of',
    category: 'event',
    description: 'Pre-event prep email at T-3 days, day-of agenda, post-event recap.',
    recommendedFor: ['saas', 'b2b', 'events'],
    locale: 'en',
    steps: 3,
    trigger: { type: 'form_submit', config: { formSlug: 'in-person-event-rsvp' } },
    nodes: [
      n('t', 'trigger', { triggerType: 'form_submit', formSlug: 'in-person-event-rsvp' }),
      n('w1', 'wait', { until: { field: 'event.starts_at', offsetHours: -72 } }),
      email('e1', 'What to bring + how to get there'),
      n('w2', 'wait', { until: { field: 'event.starts_at', offsetHours: -1 } }),
      email('e2', 'See you in an hour — agenda inside'),
      n('w3', 'wait', { until: { field: 'event.starts_at', offsetHours: 24 } }),
      email('e3', 'Thanks for coming — your perks + photos'),
    ],
    edges: [
      e('e0', 't', 'w1'),
      e('e1', 'w1', 'e1'),
      e('e2', 'e1', 'w2'),
      e('e3', 'w2', 'e2'),
      e('e4', 'e2', 'w3'),
      e('e5', 'w3', 'e3'),
    ],
  },
  {
    slug: 'event-no-show-recovery',
    name: 'Webinar — No-show recovery',
    category: 'event',
    description: 'Registrants who did not attend: send recording + reschedule offer.',
    recommendedFor: ['saas', 'b2b'],
    locale: 'en',
    steps: 2,
    trigger: { type: 'api_event', config: { eventName: 'webinar_no_show' } },
    nodes: [
      n('t', 'trigger', { triggerType: 'api_event', eventName: 'webinar_no_show' }),
      wait('w1', 0, 2),
      email('e1', 'Sorry we missed you — watch the recording'),
      wait('w2', 5),
      email('e2', 'Want to try again? Upcoming sessions'),
    ],
    edges: [
      e('e0', 't', 'w1'),
      e('e1', 'w1', 'e1'),
      e('e2', 'e1', 'w2'),
      e('e3', 'w2', 'e2'),
    ],
  },

  // ─── Feedback / NPS / CSAT ────────────────────────────────────────────────
  {
    slug: 'csat-survey-7-day',
    name: 'CSAT survey — 7 days post-purchase',
    category: 'feedback_nps',
    description: 'Single-question CSAT after delivery; auto-route low scores to support.',
    recommendedFor: ['ecommerce', 'saas'],
    locale: 'en',
    steps: 1,
    trigger: { type: 'date_field', config: { field: 'last_order_at', daysAfter: 7 } },
    nodes: [
      n('t', 'trigger', { triggerType: 'date_field', field: 'last_order_at', daysAfter: 7 }),
      email('e1', 'How would you rate your experience?'),
      wait('w1', 3),
      n('c1', 'condition', { rule: { type: 'csat_score_lte', value: 3 } }),
      n('a1', 'assign_task', { taskType: 'low-csat-followup' }),
    ],
    edges: [e('e0', 't', 'e1'), e('e1', 'e1', 'w1'), e('e2', 'w1', 'c1'), e('e3', 'c1', 'a1', 'true')],
  },

  // ─── Review request ──────────────────────────────────────────────────────
  {
    slug: 'review-request-promoter-only',
    name: 'Review — Promoter-only request',
    category: 'review_request',
    description: 'Only asks for a public review from contacts who scored 9–10 on NPS.',
    recommendedFor: ['ecommerce', 'saas'],
    locale: 'en',
    steps: 1,
    trigger: { type: 'api_event', config: { eventName: 'nps_promoter' } },
    nodes: [
      n('t', 'trigger', { triggerType: 'api_event', eventName: 'nps_promoter' }),
      wait('w1', 1),
      email('e1', 'Loved your experience? Share it publicly'),
    ],
    edges: [e('e0', 't', 'w1'), e('e1', 'w1', 'e1')],
  },
  {
    slug: 'review-request-post-delivery',
    name: 'Review — Post-delivery (timed)',
    category: 'review_request',
    description: 'Asks for product review 14 days after delivery, reminder at 21 days.',
    recommendedFor: ['ecommerce'],
    locale: 'en',
    steps: 2,
    trigger: { type: 'api_event', config: { eventName: 'order_delivered' } },
    nodes: [
      n('t', 'trigger', { triggerType: 'api_event', eventName: 'order_delivered' }),
      wait('w1', 14),
      email('e1', 'How is your {{product.name}}?'),
      wait('w2', 7),
      n('c1', 'condition', { rule: { type: 'review_submitted_within', days: 7 } }),
      email('e2', 'Quick favor — a 30-second review?'),
    ],
    edges: [
      e('e0', 't', 'w1'),
      e('e1', 'w1', 'e1'),
      e('e2', 'e1', 'w2'),
      e('e3', 'w2', 'c1'),
      e('e4', 'c1', 'e2', 'false'),
    ],
  },

  // ─── Cross-sell variants ──────────────────────────────────────────────────
  {
    slug: 'cross-sell-category-affinity',
    name: 'Cross-sell — Category affinity',
    category: 'cross_sell',
    description: 'Promotes items from a complementary category 21 days after first purchase.',
    recommendedFor: ['ecommerce'],
    locale: 'en',
    steps: 1,
    trigger: { type: 'purchase_event', config: {} },
    nodes: [
      n('t', 'trigger', { triggerType: 'purchase_event' }),
      wait('w1', 21),
      email('e1', 'Customers who bought {{order.firstItem.category}} also love…'),
    ],
    edges: [e('e0', 't', 'w1'), e('e1', 'w1', 'e1')],
  },

  // ─── Onboarding variants ──────────────────────────────────────────────────
  {
    slug: 'onboarding-progressive-profiling',
    name: 'Onboarding — Progressive profiling',
    category: 'onboarding',
    description: 'Builds a richer profile by asking 1 question per email across 4 emails.',
    recommendedFor: ['saas', 'newsletter', 'ecommerce'],
    locale: 'en',
    steps: 4,
    trigger: { type: 'list_subscribe', config: {} },
    nodes: [
      n('t', 'trigger', { triggerType: 'list_subscribe' }),
      email('e1', 'Welcome — what brought you here?'),
      wait('w1', 2),
      email('e2', 'Which topic interests you most?'),
      wait('w2', 3),
      email('e3', 'Where are you based?'),
      wait('w3', 4),
      email('e4', 'A thank-you for sharing — your gift inside'),
    ],
    edges: [
      e('e0', 't', 'e1'),
      e('e1', 'e1', 'w1'),
      e('e2', 'w1', 'e2'),
      e('e3', 'e2', 'w2'),
      e('e4', 'w2', 'e3'),
      e('e5', 'e3', 'w3'),
      e('e6', 'w3', 'e4'),
    ],
  },
  {
    slug: 'onboarding-feature-activation',
    name: 'SaaS — Feature activation nudges',
    category: 'onboarding',
    description: 'For each unused critical feature, send a focused activation email.',
    recommendedFor: ['saas'],
    locale: 'en',
    steps: 3,
    trigger: { type: 'api_event', config: { eventName: 'inactive_critical_feature' } },
    nodes: [
      n('t', 'trigger', { triggerType: 'api_event', eventName: 'inactive_critical_feature' }),
      email('e1', 'Try {{feature.name}} in 60 seconds'),
      wait('w1', 3),
      n('c1', 'condition', { rule: { type: 'feature_used', feature: '{{feature.id}}' } }),
      email('e2', 'Still on the fence? Here is what others do'),
      wait('w2', 5),
      email('e3', 'Last tip — book a 1-on-1 setup call'),
    ],
    edges: [
      e('e0', 't', 'e1'),
      e('e1', 'e1', 'w1'),
      e('e2', 'w1', 'c1'),
      e('e3', 'c1', 'e2', 'false'),
      e('e4', 'e2', 'w2'),
      e('e5', 'w2', 'e3'),
    ],
  },

  // ─── Churn prevention variants ────────────────────────────────────────────
  {
    slug: 'churn-prevention-downgrade-saver',
    name: 'Churn prevention — Downgrade saver',
    category: 'churn_prevention',
    description: 'Fires when a subscriber requests downgrade — offer alternative + save offer.',
    recommendedFor: ['saas', 'subscription'],
    locale: 'en',
    steps: 1,
    trigger: { type: 'api_event', config: { eventName: 'plan_downgrade_requested' } },
    nodes: [
      n('t', 'trigger', { triggerType: 'api_event', eventName: 'plan_downgrade_requested' }),
      email('e1', 'Before you downgrade — 50% off for 3 months'),
    ],
    edges: [e('e0', 't', 'e1')],
  },

  // ─── Date-triggered: SK + CZ holidays ─────────────────────────────────────
  {
    slug: 'sk-name-day-greeting',
    name: 'SK meniny — meninové prianie',
    category: 'date_triggered',
    description: 'Pošle blahoprianie na slovenský sviatok mena kontaktu.',
    recommendedFor: ['ecommerce', 'fitness', 'cz-sk-saas'],
    locale: 'sk',
    steps: 1,
    trigger: { type: 'name_day_today', config: { locale: 'sk' } },
    nodes: [
      n('t', 'trigger', { triggerType: 'name_day_today' }),
      email('e1', 'Všetko najlepšie k meninám, {{contact.first_name|vocative}}!'),
    ],
    edges: [e('e0', 't', 'e1')],
  },
  {
    slug: 'cz-christmas-week',
    name: 'CZ Vánoce — týden před',
    category: 'date_triggered',
    description: 'Vánoční kampaň 7 dní před Štědrým dnem (24.12.).',
    recommendedFor: ['ecommerce', 'cz-sk'],
    locale: 'cs',
    steps: 1,
    trigger: { type: 'n_days_before_holiday', config: { holiday: 'christmas_eve', daysBefore: 7 } },
    nodes: [
      n('t', 'trigger', {
        triggerType: 'n_days_before_holiday',
        holiday: 'christmas_eve',
        daysBefore: 7,
      }),
      email('e1', 'Vánoční nabídka — doručíme včas'),
    ],
    edges: [e('e0', 't', 'e1')],
  },
  {
    slug: 'cz-st-nicholas',
    name: 'CZ Mikuláš — 5.12.',
    category: 'date_triggered',
    description: 'Předmikulášská kampaň 3 dny před Mikulášem (5.12.).',
    recommendedFor: ['ecommerce', 'cz-sk'],
    locale: 'cs',
    steps: 1,
    trigger: { type: 'n_days_before_holiday', config: { holiday: 'st_nicholas', daysBefore: 3 } },
    nodes: [
      n('t', 'trigger', {
        triggerType: 'n_days_before_holiday',
        holiday: 'st_nicholas',
        daysBefore: 3,
      }),
      email('e1', 'Mikulášské překvapení čeká'),
    ],
    edges: [e('e0', 't', 'e1')],
  },
  {
    slug: 'cz-mothers-day',
    name: 'CZ Den matek — 2. neděle května',
    category: 'date_triggered',
    description: 'Kampaň 5 dnů před Dnem matek (2. neděle v květnu).',
    recommendedFor: ['ecommerce', 'beauty', 'cz-sk'],
    locale: 'cs',
    steps: 1,
    trigger: { type: 'n_days_before_holiday', config: { holiday: 'mothers_day', daysBefore: 5 } },
    nodes: [
      n('t', 'trigger', {
        triggerType: 'n_days_before_holiday',
        holiday: 'mothers_day',
        daysBefore: 5,
      }),
      email('e1', 'Tip na Den matek — slevy na vybrané dárky'),
    ],
    edges: [e('e0', 't', 'e1')],
  },
  {
    slug: 'anniversary-signup',
    name: 'Anniversary — Sign-up anniversary',
    category: 'date_triggered',
    description: 'Celebrate the contact 1 year after they signed up — with a thank-you discount.',
    recommendedFor: ['ecommerce', 'saas', 'newsletter'],
    locale: 'en',
    steps: 1,
    trigger: { type: 'date_field', config: { field: 'created_at', annualOn: true } },
    nodes: [
      n('t', 'trigger', { triggerType: 'date_field', field: 'created_at', annualOn: true }),
      email('e1', 'A year together — here is 15% off as a thank-you'),
    ],
    edges: [e('e0', 't', 'e1')],
  },

  // ─── Subscription renewal — failed card ───────────────────────────────────
  {
    slug: 'subscription-card-expiring',
    name: 'Subscription — Card expiring',
    category: 'subscription_renewal',
    description: 'Reminder 14 days before card expires + auto-task for support escalation.',
    recommendedFor: ['saas', 'subscription'],
    locale: 'en',
    steps: 2,
    trigger: { type: 'date_field', config: { field: 'card_expires_at', daysBefore: 14 } },
    nodes: [
      n('t', 'trigger', { triggerType: 'date_field', field: 'card_expires_at', daysBefore: 14 }),
      email('e1', 'Your card on file expires soon — update it'),
      wait('w1', 10),
      n('c1', 'condition', { rule: { type: 'card_updated_within', days: 10 } }),
      email('e2', "Heads-up: we'll retry payment when your subscription renews"),
    ],
    edges: [
      e('e0', 't', 'e1'),
      e('e1', 'e1', 'w1'),
      e('e2', 'w1', 'c1'),
      e('e3', 'c1', 'e2', 'false'),
    ],
  },

  // ─── Transactional ────────────────────────────────────────────────────────
  {
    slug: 'transactional-order-confirmation',
    name: 'Transactional — Order confirmation',
    category: 'transactional',
    description: 'Instant order confirmation email with receipt + delivery ETA.',
    recommendedFor: ['ecommerce'],
    locale: 'en',
    steps: 1,
    trigger: { type: 'purchase_event', config: {} },
    nodes: [
      n('t', 'trigger', { triggerType: 'purchase_event' }),
      email('e1', 'Order #{{order.id}} — receipt + delivery ETA'),
    ],
    edges: [e('e0', 't', 'e1')],
  },
  {
    slug: 'transactional-password-reset',
    name: 'Transactional — Password reset',
    category: 'transactional',
    description: 'Immediately deliver password reset link triggered by an API event.',
    recommendedFor: ['saas', 'ecommerce'],
    locale: 'en',
    steps: 1,
    trigger: { type: 'api_event', config: { eventName: 'password_reset_requested' } },
    nodes: [
      n('t', 'trigger', { triggerType: 'api_event', eventName: 'password_reset_requested' }),
      email('e1', 'Reset your password'),
    ],
    edges: [e('e0', 't', 'e1')],
  },
  {
    slug: 'transactional-shipping-cascade',
    name: 'Transactional — Shipping email→SMS cascade',
    category: 'transactional',
    description: 'Email when order ships, SMS escalation if email is not opened in 24h.',
    recommendedFor: ['ecommerce'],
    locale: 'en',
    steps: 2,
    trigger: { type: 'api_event', config: { eventName: 'order_shipped' } },
    nodes: [
      n('t', 'trigger', { triggerType: 'api_event', eventName: 'order_shipped' }),
      email('e1', 'Your order shipped'),
      wait('w1', 1),
      n('c1', 'condition', { rule: { type: 'email_opened_within', days: 1 } }),
      sms('s1', 'Heads up: your order is on its way — track {{order.trackUrl}}'),
    ],
    edges: [
      e('e0', 't', 'e1'),
      e('e1', 'e1', 'w1'),
      e('e2', 'w1', 'c1'),
      e('e3', 'c1', 's1', 'false'),
    ],
  },

  // ─── SaaS lifecycle (#215 expansion) ─────────────────────────────────────────
  {
    slug: 'saas-trial-expiry-3day',
    name: 'Trial expiry — 3-day countdown',
    category: 'saas_lifecycle',
    description: 'Urgency sequence: 3 days before trial ends, 1 day before, day of expiry.',
    recommendedFor: ['saas'],
    locale: 'en',
    steps: 3,
    trigger: { type: 'api_event', config: { eventName: 'trial_will_expire' } },
    nodes: [
      n('t', 'trigger', { triggerType: 'api_event', eventName: 'trial_will_expire' }),
      email('e1', 'Your trial ends in 3 days — here\'s how to keep your progress'),
      wait('w1', 2),
      email('e2', 'Last 24 hours — upgrade now and lock in your data'),
      wait('w2', 0, 20),
      email('e3', 'Your trial just ended — pick a plan to continue'),
    ],
    edges: [e('e0','t','e1'),e('e1','e1','w1'),e('e2','w1','e2'),e('e3','e2','w2'),e('e4','w2','e3')],
  },
  {
    slug: 'saas-feature-adoption',
    name: 'Feature adoption — 3-nudge sequence',
    category: 'saas_lifecycle',
    description: 'Guide users to a key feature they haven\'t activated yet.',
    recommendedFor: ['saas'],
    locale: 'en',
    steps: 3,
    trigger: { type: 'api_event', config: { eventName: 'feature_not_used' } },
    nodes: [
      n('t', 'trigger', { triggerType: 'api_event', eventName: 'feature_not_used' }),
      email('e1', 'Did you know you have {{feature.name}} available?'),
      wait('w1', 3),
      n('c1', 'condition', { rule: { type: 'api_event_occurred', eventName: 'feature_activated' } }),
      email('e2', 'Quick tip: how top teams use {{feature.name}}'),
      wait('w2', 4),
      email('e3', 'One-click setup for {{feature.name}} — takes 2 minutes'),
    ],
    edges: [e('e0','t','e1'),e('e1','e1','w1'),e('e2','w1','c1'),e('e3','c1','e2','false'),e('e4','e2','w2'),e('e5','w2','e3')],
  },
  {
    slug: 'saas-csm-check-in-30d',
    name: 'CSM check-in at 30 days',
    category: 'saas_lifecycle',
    description: 'Automated health-check from customer success at day 30.',
    recommendedFor: ['saas', 'b2b'],
    locale: 'en',
    steps: 2,
    trigger: { type: 'api_event', config: { eventName: 'account_created' } },
    nodes: [
      n('t', 'trigger', { triggerType: 'api_event', eventName: 'account_created' }),
      wait('w1', 30),
      email('e1', 'How\'s it going, {{contact.first_name}}? Quick check-in from your CSM'),
      wait('w2', 5),
      n('c1', 'condition', { rule: { type: 'email_replied' } }),
      email('e2', 'Friendly follow-up — can I help with anything?'),
    ],
    edges: [e('e0','t','w1'),e('e1','w1','e1'),e('e2','e1','w2'),e('e3','w2','c1'),e('e4','c1','e2','false')],
  },
  {
    slug: 'saas-pql-upsell',
    name: 'Product-qualified lead upsell',
    category: 'saas_lifecycle',
    description: 'Triggered when a free user hits a usage threshold — present upgrade path.',
    recommendedFor: ['saas'],
    locale: 'en',
    steps: 3,
    trigger: { type: 'api_event', config: { eventName: 'usage_limit_reached' } },
    nodes: [
      n('t', 'trigger', { triggerType: 'api_event', eventName: 'usage_limit_reached' }),
      email('e1', 'You\'ve hit your limit — here\'s how to unlock more'),
      wait('w1', 2),
      email('e2', 'Teams on {{plan.name}} get 10× the capacity — see what\'s included'),
      wait('w2', 5),
      email('e3', 'Last chance — upgrade this week and get 20% off your first year'),
    ],
    edges: [e('e0','t','e1'),e('e1','e1','w1'),e('e2','w1','e2'),e('e3','e2','w2'),e('e4','w2','e3')],
  },
  {
    slug: 'saas-mql-to-sql-handoff',
    name: 'MQL → SQL sales handoff',
    category: 'saas_lifecycle',
    description: 'Marketing-qualified lead scores high → route to sales with context email.',
    recommendedFor: ['saas', 'b2b'],
    locale: 'en',
    steps: 2,
    trigger: { type: 'tag_added', config: { tagName: 'mql' } },
    nodes: [
      n('t', 'trigger', { triggerType: 'tag_added', tagName: 'mql' }),
      email('e1', '{{contact.first_name}}, your account is ready for a quick demo'),
      wait('w1', 2),
      n('c1', 'condition', { rule: { type: 'email_clicked' } }),
      email('e2', 'Let me know a time that works — 15-minute call, no pressure'),
    ],
    edges: [e('e0','t','e1'),e('e1','e1','w1'),e('e2','w1','c1'),e('e3','c1','e2','false')],
  },
  {
    slug: 'saas-churned-reactivation',
    name: 'Churned customer reactivation',
    category: 'saas_lifecycle',
    description: 'Win back cancelled accounts with new features + offer.',
    recommendedFor: ['saas'],
    locale: 'en',
    steps: 3,
    trigger: { type: 'api_event', config: { eventName: 'subscription_cancelled' } },
    nodes: [
      n('t', 'trigger', { triggerType: 'api_event', eventName: 'subscription_cancelled' }),
      wait('w1', 7),
      email('e1', 'We\'ve added new features since you left — take a look'),
      wait('w2', 14),
      email('e2', 'Come back — first month free, no credit card required'),
      wait('w3', 30),
      email('e3', 'One last thought before we say goodbye'),
    ],
    edges: [e('e0','t','w1'),e('e1','w1','e1'),e('e2','e1','w2'),e('e3','w2','e2'),e('e4','e2','w3'),e('e5','w3','e3')],
  },
  {
    slug: 'saas-annual-renewal',
    name: 'Annual plan renewal sequence',
    category: 'saas_lifecycle',
    description: 'Proactive renewal: 60d / 30d / 14d / 7d / 1d reminders.',
    recommendedFor: ['saas', 'subscription'],
    locale: 'en',
    steps: 5,
    trigger: { type: 'api_event', config: { eventName: 'renewal_approaching_60d' } },
    nodes: [
      n('t', 'trigger', { triggerType: 'api_event', eventName: 'renewal_approaching_60d' }),
      email('e1', 'Your plan renews in 60 days — here\'s what\'s new this year'),
      wait('w1', 30),
      email('e2', '30 days to renewal — lock in your rate now'),
      wait('w2', 16),
      email('e3', '14 days left — renew to avoid service interruption'),
      wait('w3', 7),
      email('e4', 'One week to go — renew your plan'),
      wait('w4', 6),
      email('e5', 'Renewing tomorrow — everything you need to know'),
    ],
    edges: [e('e0','t','e1'),e('e1','e1','w1'),e('e2','w1','e2'),e('e3','e2','w2'),e('e4','w2','e3'),e('e5','e3','w3'),e('e6','w3','e4'),e('e7','e4','w4'),e('e8','w4','e5')],
  },
  {
    slug: 'saas-downgrade-saver',
    name: 'Downgrade saver',
    category: 'saas_lifecycle',
    description: 'Contact tried to downgrade — offer help + retention incentive.',
    recommendedFor: ['saas'],
    locale: 'en',
    steps: 2,
    trigger: { type: 'api_event', config: { eventName: 'downgrade_initiated' } },
    nodes: [
      n('t', 'trigger', { triggerType: 'api_event', eventName: 'downgrade_initiated' }),
      email('e1', 'Before you downgrade — can I help?'),
      wait('w1', 1),
      email('e2', 'Stay on {{plan.name}} — we\'ll extend your trial by 30 days'),
    ],
    edges: [e('e0','t','e1'),e('e1','e1','w1'),e('e2','w1','e2')],
  },

  // ─── Sales engagement (#215 expansion) ───────────────────────────────────────
  {
    slug: 'sales-cold-outreach-3touch',
    name: 'Cold outreach — 3-touch sequence',
    category: 'sales_engagement',
    description: 'Permission-based outreach: value first, follow-up, final bump.',
    recommendedFor: ['b2b', 'saas'],
    locale: 'en',
    steps: 3,
    trigger: { type: 'tag_added', config: { tagName: 'cold_prospect' } },
    nodes: [
      n('t', 'trigger', { triggerType: 'tag_added', tagName: 'cold_prospect' }),
      email('e1', '{{contact.first_name}} — quick thought on {{company.industry}}'),
      wait('w1', 4),
      n('c1', 'condition', { rule: { type: 'email_opened' } }),
      email('e2', 'Following up — worth a quick call?'),
      wait('w2', 5),
      email('e3', 'Last note from me — happy to connect when the time is right'),
    ],
    edges: [e('e0','t','e1'),e('e1','e1','w1'),e('e2','w1','c1'),e('e3','c1','e2','false'),e('e4','e2','w2'),e('e5','w2','e3')],
  },
  {
    slug: 'sales-demo-reminder',
    name: 'Demo reminder — day-before + 1h',
    category: 'sales_engagement',
    description: 'Confirm demo, send agenda, 1h reminder, post-demo followup.',
    recommendedFor: ['saas', 'b2b'],
    locale: 'en',
    steps: 3,
    trigger: { type: 'api_event', config: { eventName: 'demo_scheduled' } },
    nodes: [
      n('t', 'trigger', { triggerType: 'api_event', eventName: 'demo_scheduled' }),
      email('e1', 'Your demo is confirmed — here\'s the agenda'),
      wait('w1', 0, 20),
      email('e2', 'Reminder: your demo starts in 1 hour'),
      wait('w2', 1),
      email('e3', 'Great talking — here\'s a recap + next steps'),
    ],
    edges: [e('e0','t','e1'),e('e1','e1','w1'),e('e2','w1','e2'),e('e3','e2','w2'),e('e4','w2','e3')],
  },
  {
    slug: 'sales-proposal-followup',
    name: 'Proposal sent — follow-up sequence',
    category: 'sales_engagement',
    description: 'After proposal sent: open-check, social proof, urgency, final close.',
    recommendedFor: ['b2b', 'saas'],
    locale: 'en',
    steps: 4,
    trigger: { type: 'api_event', config: { eventName: 'proposal_sent' } },
    nodes: [
      n('t', 'trigger', { triggerType: 'api_event', eventName: 'proposal_sent' }),
      email('e1', 'Your proposal — any questions before you review?'),
      wait('w1', 3),
      n('c1', 'condition', { rule: { type: 'email_opened' } }),
      email('e2', 'How other {{company.industry}} teams made this decision'),
      wait('w2', 4),
      email('e3', 'A few things worth knowing before you decide'),
      wait('w3', 5),
      email('e4', 'Closing the loop — what\'s holding things up?'),
    ],
    edges: [e('e0','t','e1'),e('e1','e1','w1'),e('e2','w1','c1'),e('e3','c1','e2','false'),e('e4','e2','w2'),e('e5','w2','e3'),e('e6','e3','w3'),e('e7','w3','e4')],
  },
  {
    slug: 'sales-deal-won-onboarding',
    name: 'Deal won → onboarding kickoff',
    category: 'sales_engagement',
    description: 'Hand off from sales to CS: welcome, intro call, setup checklist.',
    recommendedFor: ['saas', 'b2b'],
    locale: 'en',
    steps: 3,
    trigger: { type: 'api_event', config: { eventName: 'deal_won' } },
    nodes: [
      n('t', 'trigger', { triggerType: 'api_event', eventName: 'deal_won' }),
      email('e1', 'Welcome to {{org.name}} — here\'s how we get started'),
      wait('w1', 1),
      email('e2', 'Your onboarding call is booked — here\'s what to prepare'),
      wait('w2', 5),
      email('e3', 'Setup checklist — 5 things to do in your first week'),
    ],
    edges: [e('e0','t','e1'),e('e1','e1','w1'),e('e2','w1','e2'),e('e3','e2','w2'),e('e4','w2','e3')],
  },
  {
    slug: 'sales-deal-lost-reactivation',
    name: 'Deal lost — 90-day reactivation',
    category: 'sales_engagement',
    description: 'Re-engage lost deals with updated value prop after 90 days.',
    recommendedFor: ['saas', 'b2b'],
    locale: 'en',
    steps: 2,
    trigger: { type: 'api_event', config: { eventName: 'deal_lost' } },
    nodes: [
      n('t', 'trigger', { triggerType: 'api_event', eventName: 'deal_lost' }),
      wait('w1', 90),
      email('e1', 'A lot has changed in the last 90 days — worth a quick look?'),
      wait('w2', 14),
      email('e2', 'Still thinking about {{org.name}}? Here\'s a fresh perspective'),
    ],
    edges: [e('e0','t','w1'),e('e1','w1','e1'),e('e2','e1','w2'),e('e3','w2','e2')],
  },

  // ─── E-commerce expansion (#215) ─────────────────────────────────────────────
  {
    slug: 'ecom-price-drop-alert',
    name: 'Price drop alert — wishlist item',
    category: 'browse_abandonment',
    description: 'Alert contacts when a wishlisted product drops in price.',
    recommendedFor: ['ecommerce'],
    locale: 'en',
    steps: 1,
    trigger: { type: 'api_event', config: { eventName: 'price_dropped' } },
    nodes: [
      n('t', 'trigger', { triggerType: 'api_event', eventName: 'price_dropped' }),
      email('e1', 'Price drop! {{product.name}} is now {{product.price}}'),
    ],
    edges: [e('e0','t','e1')],
  },
  {
    slug: 'ecom-vip-early-access',
    name: 'VIP early access — new product launch',
    category: 'vip_loyalty',
    description: 'Give VIP segment 24h early access before public launch.',
    recommendedFor: ['ecommerce'],
    locale: 'en',
    steps: 2,
    trigger: { type: 'tag_added', config: { tagName: 'vip' } },
    nodes: [
      n('t', 'trigger', { triggerType: 'api_event', eventName: 'product_launch_imminent' }),
      email('e1', 'VIPs only: 24h early access to {{product.name}}'),
      wait('w1', 0, 20),
      email('e2', 'Early access closes in 4 hours — {{product.name}} launches soon'),
    ],
    edges: [e('e0','t','e1'),e('e1','e1','w1'),e('e2','w1','e2')],
  },
  {
    slug: 'ecom-subscription-pause',
    name: 'Subscription pause → save',
    category: 'subscription_renewal',
    description: 'When customer tries to pause subscription, offer skip or discount.',
    recommendedFor: ['ecommerce', 'subscription'],
    locale: 'en',
    steps: 2,
    trigger: { type: 'api_event', config: { eventName: 'subscription_pause_requested' } },
    nodes: [
      n('t', 'trigger', { triggerType: 'api_event', eventName: 'subscription_pause_requested' }),
      email('e1', 'Before you pause — would a skip month help?'),
      wait('w1', 2),
      email('e2', 'We\'ll miss you — your subscription is paused until {{subscription.resumeDate}}'),
    ],
    edges: [e('e0','t','e1'),e('e1','e1','w1'),e('e2','w1','e2')],
  },
  {
    slug: 'ecom-bfcm-presale',
    name: 'Black Friday / Cyber Monday pre-sale',
    category: 'date_triggered',
    description: '3-email BFCM countdown: teaser → launch → last-chance.',
    recommendedFor: ['ecommerce'],
    locale: 'en',
    steps: 3,
    trigger: { type: 'api_event', config: { eventName: 'bfcm_campaign_start' } },
    nodes: [
      n('t', 'trigger', { triggerType: 'api_event', eventName: 'bfcm_campaign_start' }),
      email('e1', 'Something big is coming — be the first to know'),
      wait('w1', 2),
      email('e2', 'Our biggest sale of the year starts NOW — up to {{sale.discount}}% off'),
      wait('w2', 3),
      email('e3', 'Last chance — sale ends at midnight'),
    ],
    edges: [e('e0','t','e1'),e('e1','e1','w1'),e('e2','w1','e2'),e('e3','e2','w2'),e('e4','w2','e3')],
  },
  {
    slug: 'ecom-post-refund-recovery',
    name: 'Post-refund recovery',
    category: 'post_purchase',
    description: 'After a refund: acknowledge → understand reason → alternative offer.',
    recommendedFor: ['ecommerce'],
    locale: 'en',
    steps: 2,
    trigger: { type: 'api_event', config: { eventName: 'refund_processed' } },
    nodes: [
      n('t', 'trigger', { triggerType: 'api_event', eventName: 'refund_processed' }),
      email('e1', 'Refund confirmed — we\'re sorry it didn\'t work out'),
      wait('w1', 3),
      email('e2', 'What went wrong? Your feedback shapes our next products'),
    ],
    edges: [e('e0','t','e1'),e('e1','e1','w1'),e('e2','w1','e2')],
  },
  {
    slug: 'ecom-product-launch-waitlist',
    name: 'Product launch — waitlist notification',
    category: 'lead_nurture',
    description: 'Notify waitlist when product becomes available.',
    recommendedFor: ['ecommerce', 'saas'],
    locale: 'en',
    steps: 2,
    trigger: { type: 'api_event', config: { eventName: 'waitlist_product_available' } },
    nodes: [
      n('t', 'trigger', { triggerType: 'api_event', eventName: 'waitlist_product_available' }),
      email('e1', 'It\'s here! {{product.name}} is now available — you\'re first in line'),
      wait('w1', 1),
      n('c1', 'condition', { rule: { type: 'email_clicked' } }),
      email('e2', 'Still interested in {{product.name}}? Stock is limited'),
    ],
    edges: [e('e0','t','e1'),e('e1','e1','w1'),e('e2','w1','c1'),e('e3','c1','e2','false')],
  },

  // ─── Re-engagement (#215 expansion) ──────────────────────────────────────────
  {
    slug: 'reengagement-180-day',
    name: 'Re-engagement — 180-day lapsed',
    category: 're_engagement',
    description: 'Win back contacts silent for 180 days before sunsetting.',
    recommendedFor: ['ecommerce', 'newsletter'],
    locale: 'en',
    steps: 3,
    trigger: { type: 'api_event', config: { eventName: 'contact_lapsed_180d' } },
    nodes: [
      n('t', 'trigger', { triggerType: 'api_event', eventName: 'contact_lapsed_180d' }),
      email('e1', 'We miss you — here\'s what\'s new'),
      wait('w1', 7),
      n('c1', 'condition', { rule: { type: 'email_opened' } }),
      email('e2', 'One more thing before we part ways'),
      wait('w2', 7),
      n('c2', 'condition', { rule: { type: 'email_opened' } }),
      n('a1', 'add_tag', { tagName: 'sunset_candidate' }),
    ],
    edges: [e('e0','t','e1'),e('e1','e1','w1'),e('e2','w1','c1'),e('e3','c1','e2','false'),e('e4','e2','w2'),e('e5','w2','c2'),e('e6','c2','a1','false')],
  },
  {
    slug: 'reengagement-sunset-policy',
    name: 'Sunset policy — final unsubscribe',
    category: 're_engagement',
    description: 'Last opt-in confirmation before suppressing cold contacts.',
    recommendedFor: ['ecommerce', 'newsletter', 'b2b'],
    locale: 'en',
    steps: 2,
    trigger: { type: 'tag_added', config: { tagName: 'sunset_candidate' } },
    nodes: [
      n('t', 'trigger', { triggerType: 'tag_added', tagName: 'sunset_candidate' }),
      email('e1', 'Should we keep in touch? Click to stay subscribed'),
      wait('w1', 14),
      n('c1', 'condition', { rule: { type: 'email_clicked' } }),
      n('a1', 'add_tag', { tagName: 'unsubscribed_sunset' }),
    ],
    edges: [e('e0','t','e1'),e('e1','e1','w1'),e('e2','w1','c1'),e('e3','c1','a1','false')],
  },
  {
    slug: 'reengagement-preference-update',
    name: 'Email preference update request',
    category: 're_engagement',
    description: 'Ask disengaged contacts to update frequency/topic preferences.',
    recommendedFor: ['newsletter', 'b2b'],
    locale: 'en',
    steps: 1,
    trigger: { type: 'api_event', config: { eventName: 'contact_lapsed_90d' } },
    nodes: [
      n('t', 'trigger', { triggerType: 'api_event', eventName: 'contact_lapsed_90d' }),
      email('e1', 'What would you like to hear from us? Update your preferences'),
    ],
    edges: [e('e0','t','e1')],
  },
  {
    slug: 'reengagement-list-hygiene',
    name: 'List hygiene — quarterly purge',
    category: 're_engagement',
    description: 'Quarterly cleanup: confirm active interest or auto-suppress.',
    recommendedFor: ['newsletter', 'ecommerce'],
    locale: 'en',
    steps: 2,
    trigger: { type: 'api_event', config: { eventName: 'quarterly_hygiene_check' } },
    nodes: [
      n('t', 'trigger', { triggerType: 'api_event', eventName: 'quarterly_hygiene_check' }),
      email('e1', 'Quick question: still want to hear from us?'),
      wait('w1', 10),
      n('c1', 'condition', { rule: { type: 'email_opened' } }),
      n('a1', 'add_tag', { tagName: 'hygiene_suppressed' }),
    ],
    edges: [e('e0','t','e1'),e('e1','e1','w1'),e('e2','w1','c1'),e('e3','c1','a1','false')],
  },

  // ─── Compliance / GDPR (#215 expansion) ──────────────────────────────────────
  {
    slug: 'gdpr-consent-renewal',
    name: 'GDPR consent renewal',
    category: 'compliance',
    description: 'Re-obtain consent before it expires (1 year validity).',
    recommendedFor: ['ecommerce', 'b2b', 'newsletter'],
    locale: 'en',
    steps: 2,
    trigger: { type: 'api_event', config: { eventName: 'consent_expiring_30d' } },
    nodes: [
      n('t', 'trigger', { triggerType: 'api_event', eventName: 'consent_expiring_30d' }),
      email('e1', 'Please confirm you still want to hear from us — takes 1 click'),
      wait('w1', 14),
      n('c1', 'condition', { rule: { type: 'email_clicked' } }),
      email('e2', 'Last chance to renew your subscription preferences'),
    ],
    edges: [e('e0','t','e1'),e('e1','e1','w1'),e('e2','w1','c1'),e('e3','c1','e2','false')],
  },
  {
    slug: 'gdpr-data-export-ready',
    name: 'GDPR data export ready',
    category: 'compliance',
    description: 'Notify contact when their data export download is ready.',
    recommendedFor: ['saas', 'ecommerce', 'b2b'],
    locale: 'en',
    steps: 1,
    trigger: { type: 'api_event', config: { eventName: 'data_export_ready' } },
    nodes: [
      n('t', 'trigger', { triggerType: 'api_event', eventName: 'data_export_ready' }),
      email('e1', 'Your data export is ready — download within 72 hours'),
    ],
    edges: [e('e0','t','e1')],
  },
  {
    slug: 'gdpr-account-deletion-confirm',
    name: 'Account deletion confirmation',
    category: 'compliance',
    description: 'Confirm account deletion with grace period + final data download offer.',
    recommendedFor: ['saas', 'ecommerce'],
    locale: 'en',
    steps: 2,
    trigger: { type: 'api_event', config: { eventName: 'account_deletion_requested' } },
    nodes: [
      n('t', 'trigger', { triggerType: 'api_event', eventName: 'account_deletion_requested' }),
      email('e1', 'We\'ve received your deletion request — your account closes in 30 days'),
      wait('w1', 25),
      email('e2', 'Final reminder: your account closes in 5 days'),
    ],
    edges: [e('e0','t','e1'),e('e1','e1','w1'),e('e2','w1','e2')],
  },
  {
    slug: 'gdpr-cs-consent-renewal',
    name: 'Souhlas se zpracováním — obnovení (CS)',
    category: 'compliance',
    description: 'Český souhlas GDPR — obnovení před expirací.',
    recommendedFor: ['ecommerce', 'b2b', 'newsletter'],
    locale: 'cs',
    steps: 2,
    trigger: { type: 'api_event', config: { eventName: 'consent_expiring_30d' } },
    nodes: [
      n('t', 'trigger', { triggerType: 'api_event', eventName: 'consent_expiring_30d' }),
      email('e1', 'Váš souhlas se zpracováním brzy vyprší — obnovte ho jedním kliknutím'),
      wait('w1', 14),
      email('e2', 'Poslední možnost: potvrďte svůj souhlas se zasíláním'),
    ],
    edges: [e('e0','t','e1'),e('e1','e1','w1'),e('e2','w1','e2')],
  },

  // ─── Blog & content (#337 + #215) ────────────────────────────────────────────
  {
    slug: 'blog-new-post-notify',
    name: 'New blog post — subscriber notification',
    category: 'blog_content',
    description: 'Auto-send to newsletter list when a new blog post is published.',
    recommendedFor: ['newsletter', 'saas', 'b2b'],
    locale: 'en',
    steps: 1,
    trigger: { type: 'api_event', config: { eventName: 'new_blog_post_published' } },
    nodes: [
      n('t', 'trigger', { triggerType: 'api_event', eventName: 'new_blog_post_published' }),
      email('e1', 'New post: {{blog.title}}'),
    ],
    edges: [e('e0','t','e1')],
  },
  {
    slug: 'blog-new-post-cs',
    name: 'Nový blogový příspěvek — notifikace (CS)',
    category: 'blog_content',
    description: 'Automatické odeslání odběratelům při publikaci nového článku.',
    recommendedFor: ['newsletter', 'saas'],
    locale: 'cs',
    steps: 1,
    trigger: { type: 'api_event', config: { eventName: 'new_blog_post_published' } },
    nodes: [
      n('t', 'trigger', { triggerType: 'api_event', eventName: 'new_blog_post_published' }),
      email('e1', 'Nový článek: {{blog.title}}'),
    ],
    edges: [e('e0','t','e1')],
  },
  {
    slug: 'blog-content-upgrade-lead-magnet',
    name: 'Content upgrade — lead magnet delivery',
    category: 'blog_content',
    description: 'Deliver content upgrade (PDF, checklist) after form submission on blog.',
    recommendedFor: ['saas', 'b2b', 'newsletter'],
    locale: 'en',
    steps: 2,
    trigger: { type: 'api_event', config: { eventName: 'content_upgrade_requested' } },
    nodes: [
      n('t', 'trigger', { triggerType: 'api_event', eventName: 'content_upgrade_requested' }),
      email('e1', 'Here\'s your {{lead_magnet.name}} — enjoy!'),
      wait('w1', 3),
      email('e2', 'Did {{lead_magnet.name}} help? Here\'s what to read next'),
    ],
    edges: [e('e0','t','e1'),e('e1','e1','w1'),e('e2','w1','e2')],
  },
  {
    slug: 'blog-weekly-digest',
    name: 'Weekly content digest',
    category: 'blog_content',
    description: 'Weekly summary of top posts — triggered by RSS / external feed.',
    recommendedFor: ['newsletter'],
    locale: 'en',
    steps: 1,
    trigger: { type: 'api_event', config: { eventName: 'weekly_digest_ready' } },
    nodes: [
      n('t', 'trigger', { triggerType: 'api_event', eventName: 'weekly_digest_ready' }),
      email('e1', 'This week in {{org.name}}: top {{digest.count}} articles'),
    ],
    edges: [e('e0','t','e1')],
  },
];

export function findTemplate(slug: string): WorkflowTemplate | null {
  return WORKFLOW_TEMPLATES.find((t) => t.slug === slug) ?? null;
}

export function listTemplates(filter?: {
  category?: TemplateCategory;
  locale?: WorkflowTemplate['locale'];
  recommendedFor?: string;
}): WorkflowTemplate[] {
  let list = WORKFLOW_TEMPLATES;
  if (filter?.category) list = list.filter((t) => t.category === filter.category);
  if (filter?.locale) list = list.filter((t) => t.locale === filter.locale);
  if (filter?.recommendedFor)
    list = list.filter((t) => t.recommendedFor.includes(filter.recommendedFor!));
  return list;
}
